/**************************************************************
  This file was generated by FileConcatenator.
  It combined all classes in the project to work in Codingame.
***************************************************************/

using System;
using System.Drawing;
using System.Collections.Generic;
using System.Linq;
using System.Net.WebSockets;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.ComponentModel.Design;
using System.Dynamic;
using System.Xml.Linq;
using static System.Net.Mime.MediaTypeNames;
using System.Reflection.Metadata.Ecma335;
using System.Runtime.ConstrainedExecution;
using System.Reflection;

internal static class CalculationUtil
{
    internal static int GetManhattanDistance(Point point1, Point point2)
    {
        return Math.Abs(point1.X - point2.X) + Math.Abs(point1.Y - point2.Y);
    }
}




internal class Game
{
    internal int Turn { get; private set ;} = 0;

    private readonly int _width;
    private readonly int _height;

    private Point _playerShack;
    private Point _enemyShack;

    private Inventory _playerInventory;
    private Inventory _enemyInventory;

    private List<Troll> _playerTrolls = new List<Troll>();
    private List<Troll> _enemyTrolls = new List<Troll>();
    private List<Tree> _trees = new List<Tree>();
    private List<Point> _iron = new List<Point>();

    private NeedsManager _needsManager;
    private PositionUtil _positionUtil;

    private bool[,] _isWalkable;
    private bool[,] _isWater;

    private List<Point> _targetedTrees = new List<Point>();

    private HashSet<int> _assigned;

    public Game(int width, int height)
    {
        _width = width;
        _height = height;
        
        _isWalkable = new bool[height, width];
        _isWater = new bool[height, width];

        _assigned = new HashSet<int>();
    }

    internal void Initialise()
    {
        _positionUtil = new PositionUtil(this, new PathFinder(_width, _height, _isWalkable));
        _positionUtil.InitialiseBestGrowSpots();

        _needsManager = new NeedsManager(this, _positionUtil);
    }

    internal List<string> GetActions()
    {
        _targetedTrees.Clear();

        SetAllTrollsToUnassigned();

        _needsManager.SetPriorities();

        List<Point> excludedTrees = new List<Point>();

        // Logger.Inventory("Player inventory", _playerInventory);
        // Logger.Inventory("Enemy inventory", _enemyInventory);

        Turn++;

        List<string> actions = new List<string>();

        Inventory usableInventory = _playerInventory;


        // Try to assign all priorities until we're out of trolls
        List<Need> priorities = _needsManager.GetPriorities();

        Logger.Prioirities(priorities);
        // Logger.Trolls(_playerTrolls);

        foreach (Need need in priorities)
        {
            if (_assigned.Count >= _playerTrolls.Count)
            {
                break;
            }

            // Find all trolls that can meet the need
            // Choose the best one
            // Mark it as assigned

            if (need == Need.HarvestAnyWood)
            {
                // Every troll in the game should be in one of the below states. 

                // If a troll is carrying a seed plant
                Troll? carryingSeedTroll = _playerTrolls.Where(t => !_assigned.Contains(t.Id) && t.IsCarryingAnyFruit()).FirstOrDefault();

                if (carryingSeedTroll != null)
                {
                    Logger.Message($"Troll {carryingSeedTroll.Id} is carrying a seed");
                    // plant it where it is if possible
                    if (IsGrowable(carryingSeedTroll.Position) && !HasTree(carryingSeedTroll.Position))
                    {
                        Logger.Message($"Troll {carryingSeedTroll.Id} is on a grow spot and will plant");
                        actions.Add($"PLANT {carryingSeedTroll.Id} {carryingSeedTroll.CarryingFruitType()}");
                        AssignTroll(carryingSeedTroll.Id);
                        continue;
                    }
                    else
                    {
                        Logger.Message($"Troll {carryingSeedTroll.Id} is not on a grow spot and will move to one");
                        Point growSpot = _positionUtil.GetClosestGrowableSpot(carryingSeedTroll.Position);
                        actions.Add($"MOVE {carryingSeedTroll.Id} {growSpot.X} {growSpot.Y}");
                        AssignTroll(carryingSeedTroll.Id);
                        continue;
                    }
                }

                // if a troll is carrying wood
                Troll? carryingWoodTroll = _playerTrolls.Where(t => !_assigned.Contains(t.Id) && t.IsCarryingWood()).FirstOrDefault();

                if (carryingWoodTroll != null)
                {
                    if (IsNextToShack(carryingWoodTroll.Position))
                    {
                        actions.Add($"DROP {carryingWoodTroll.Id}");
                        AssignTroll(carryingWoodTroll.Id);
                        continue;
                    }
                    else
                    {
                        actions.Add($"MOVE {carryingWoodTroll.Id} {_playerShack.X} {_playerShack.Y}");
                        AssignTroll(carryingWoodTroll.Id);
                        continue;
                    }
                }

                // If there is a nearby tree attack it
                List<Point> orderedTrees = _trees.Where(t => !_targetedTrees.Contains(t.Position)).OrderBy(t => GetManhattanDistance(t.Position, _playerShack)).Select(t => t.Position).ToList();
                //List<Point> orderedTrees = _trees.Where(t => !_targetedTrees.Contains(t.Position)).OrderBy(t => t.Size).ThenBy(t => GetManhattanDistance(t.Position, _playerShack)).Select(t => t.Position).ToList();

                Point closeTree = new Point(-1, -1);

                foreach (Point tree in orderedTrees)
                {
                    if (GetManhattanDistance(tree, _playerShack) > 3)
                    {
                        break;
                    }

                    int dist = _positionUtil.GetShortestPath(_playerShack, tree).Count;

                    if (dist <= 3)
                    {
                        closeTree = _trees.First(t => t.Position == tree).Position;
                        break;
                    }
                }

                if (closeTree != new Point(-1, -1))
                {
                    // check if a troll is on the tree
                    Troll? trollOnTree = _playerTrolls.Where(t => !_assigned.Contains(t.Id) && t.CanCarry() && t.Position == closeTree).FirstOrDefault();

                    if (trollOnTree != null)
                    {
                        actions.Add($"CHOP {trollOnTree.Id}");
                        AssignTroll(trollOnTree.Id);
                        _targetedTrees.Add(closeTree);
                        continue;
                    }
                    else
                    {
                        // Get closest troll to tree
                        Troll? closestTroll = _playerTrolls.Where(t => !_assigned.Contains(t.Id)).OrderBy(t => _positionUtil.GetShortestPath(t.Position, closeTree).Count).FirstOrDefault();

                        if (closestTroll != null)
                        {
                            actions.Add($"MOVE {closestTroll.Id} {closeTree.X} {closeTree.Y}");
                            AssignTroll(closestTroll.Id);
                            _targetedTrees.Add(closeTree);
                            continue;
                        }
                    }
                }

                // Go get a seed
                // Get the closest unassigned troll to the shack with inventory space
                if (InventoryUtil.DoesContainFruit(_playerInventory))
                {
                    Troll? closestTroll = _playerTrolls.Where(t => !_assigned.Contains(t.Id) && t.CanCarry()).OrderBy(t => _positionUtil.GetShortestPath(t.Position, _playerShack).Count).FirstOrDefault();
                    
                    if (closestTroll != null)
                    {
                        if (IsNextToShack(closestTroll.Position))
                        {
                            actions.Add($"PICK {closestTroll.Id} {InventoryUtil.GetAnyFruitType(usableInventory)}");
                            usableInventory = InventoryUtil.ChangeInventory(usableInventory, InventoryUtil.GetAnyFruitType(usableInventory), -1);
                            AssignTroll(closestTroll.Id);
                            continue;
                        }
                        else
                        {
                            actions.Add($"MOVE {closestTroll.Id} {_playerShack.X} {_playerShack.Y}");
                            AssignTroll(closestTroll.Id);
                            continue;
                        }
                    }
                }

                // If there is a far away tree attack it
            }

            // If a need can't be met log it and remove it
            if (need == Need.AttackEnemy)
            {
                string attackMove = CalculateAtackMove();

                if (!string.IsNullOrEmpty(attackMove))
                {
                    actions.Add(attackMove);
                    continue;
                }
            }

            if (NeedsManager.IsGrowNeed(need))
            {
                Logger.Message($"Trying to meet grow need {need}");

                ResourceType fruitType = NeedsManager.GetTreeType(need);

                // if a troll has a fruit of this type
                if (_playerTrolls.Any(t => t.IsCarryingFruit(fruitType) > 0))
                {
                    Logger.Message("Troll is carrying fruit" + fruitType + " and trying to find grow spot");
                    // find closest plant spot for this fruit
                    Point growSpot = _positionUtil.GetBestGrowSpot();

                    if (growSpot.X == -1 && growSpot.Y == -1)
                    {
                        Logger.Error("No grow spot found for " + fruitType);
                        continue;
                    }

                    // Get all trolls that are carrying this fruit and are not assigned yet
                    List<Troll> candidateTrolls = _playerTrolls
                        .Where(t => !_assigned.Contains(t.Id) && t.IsCarryingFruit(fruitType) > 0)
                        .ToList();

                    (Troll? closestTroll, List<Point> shortestPath) = _positionUtil.GetClosestTrollToTarget(candidateTrolls, growSpot);

                    if (closestTroll != null)
                    {
                        if (closestTroll.Position == growSpot)
                        {
                            actions.Add($"PLANT {closestTroll.Id} {fruitType.ToString()}");
                            AssignTroll(closestTroll.Id);
                            usableInventory = InventoryUtil.ChangeInventory(usableInventory, fruitType, -1);
                            continue;
                        }
                        else
                        {
                            Logger.Message($"Closest troll to move for need {need} is {closestTroll.Id} at position {closestTroll.Position} with next move {shortestPath[0]}");
                            actions.Add($"MOVE {closestTroll.Id} {shortestPath[0].X} {shortestPath[0].Y}");
                            AssignTroll(closestTroll.Id);
                            continue;
                        }
                    }
                    else
                    {
                        Logger.Error($"No close troll can be found with {fruitType}");
                    }
                }
                else
                {
                    (Troll? closestTroll, Point nextMove) = GetClosestTrollMove(usableInventory, fruitType);

                    Logger.Message($"Closest troll to move for need {need} is {closestTroll?.Id} at position {closestTroll?.Position} with next move {nextMove}");

                    if (closestTroll != null)
                    {
                        if (closestTroll.Position == nextMove)
                        {
                            // It's on the target, either harvest or pick
                            if (_positionUtil.IsTreeAtPosition(closestTroll.Position, fruitType))
                            {
                                actions.Add($"HARVEST {closestTroll.Id}");
                                AssignTroll(closestTroll.Id);
                                continue;
                            }
                            else
                            {
                                actions.Add($"PICK {closestTroll.Id} {fruitType.ToString()}");
                                usableInventory = InventoryUtil.ChangeInventory(usableInventory, fruitType, -1);
                                AssignTroll(closestTroll.Id);
                                continue;
                            }
                        }
                        else
                        {
                            actions.Add($"MOVE {closestTroll.Id} {nextMove.X} {nextMove.Y}");
                            AssignTroll(closestTroll.Id);
                            continue;
                        }
                    }
                }
            }
            
            if (NeedsManager.IsharvestNeed(need))
            {
                ResourceType fruitType = NeedsManager.GetTreeType(need);

                // if a troll has a fruit of this type
                if (_playerTrolls.Any(t => !_assigned.Contains(t.Id) && t.IsCarryingFruit(fruitType) > 0))
                {
                    Logger.Message($"Troll is carrying fruit {fruitType} and trying to find shack to drop off");
                    var troll = _playerTrolls.First(t => !_assigned.Contains(t.Id) && t.IsCarryingFruit(fruitType) > 0);

                    if (_positionUtil.IsAdjacentToShack(troll.Position) || troll.Position == _playerShack)
                    {
                        actions.Add($"DROP {troll.Id}");
                        AssignTroll(troll.Id);
                        usableInventory = InventoryUtil.ChangeInventory(usableInventory, fruitType, 1);
                        continue;
                    }

                    // Head for the shack
                    List<Point> shortestPath = _positionUtil.GetShortestPath(troll.Position, _playerShack);

                    if (shortestPath.Count > 0)
                    {
                        Point nextMove = shortestPath[0];
                        actions.Add($"MOVE {troll.Id} {nextMove.X} {nextMove.Y}");
                        AssignTroll(troll.Id);
                        continue;
                    }
                }
                else
                {
                    // Find the nearest unassigned troll, with free inventory space, to a tree of this type and send it to harvest
                    List<Troll> candidateTrolls = _playerTrolls.Where(t => !_assigned.Contains(t.Id) && t.CanCarry()).ToList();

                    List<Point> candidatePoints = new List<Point>();

                    if (need == Need.HarvestIron)
                    {
                        candidatePoints = _iron;
                    }
                    else
                    {
                        candidatePoints = _trees.Where(t => t.Type == fruitType && t.Fruits > 0).Select(t => t.Position).ToList();
                    }

                    // If we can harvest or mine then do it
                    string getAction = CanWeGetIt(candidateTrolls, candidatePoints, need);

                    if (!string.IsNullOrEmpty(getAction))
                    {
                        actions.Add(getAction);
                        continue;
                    }

                    Logger.Message("HERE");
                    Logger.Message($"Fruit type: {fruitType}");

                    foreach (var point in candidatePoints)
                    {
                        Logger.Message($"Candidate point: {point}");
                    }

                    (Troll? closestTroll, List<Point> shortestPath) = _positionUtil.GetClosestTrollToTargets(candidateTrolls, candidatePoints, 8);

                    if (closestTroll != null && shortestPath.Count > 0)
                    {
                        actions.Add($"MOVE {closestTroll.Id} {shortestPath[0].X} {shortestPath[0].Y}");
                        AssignTroll(closestTroll.Id);
                        continue;
                    }
                }

                // TODO: Deal with wood later
            }

            Logger.Error("No need could be met for " + need.ToString());
        }

        foreach (Troll troll in _playerTrolls.Where(t => !t.CanCarry() && !_assigned.Contains(t.Id)))
        {
            if (_positionUtil.IsAdjacentToShack(troll.Position) || troll.Position == _playerShack)
            {
                actions.Add($"DROP {troll.Id}");
                AssignTroll(troll.Id);
            }
            else
            {
                actions.Add($"MOVE {troll.Id} {_playerShack.X} {_playerShack.Y}");
                AssignTroll(troll.Id);
            }
            
            
        }

        if (priorities.Contains(Need.TrainTroll))
        {
            Logger.Inventory("Usable inventory for training", usableInventory);
            (int plums, int lemons, int apples, int iron) = TrainingUtil.GetBestTrollTraining(_playerTrolls.Count, usableInventory);
                        
            if (plums > 0 && lemons > 0 && apples > 0 && iron > 0)
            {
                Logger.Message($"Training troll with {plums} plums, {lemons} lemons, {apples} apples and {iron} iron");
                actions.Add($"TRAIN {plums} {lemons} {apples} {iron}");
            }
        }

        return actions;
    }

    private string CalculateAtackMove()
    {
        //Get a list of candidate enemy trees
        Point enemyShack = _enemyShack;

        List<Point> candidateTrees = new List<Point>();

        for (int y = enemyShack.Y - 2; y <= enemyShack.Y + 2; y++)
        {
            for (int x = enemyShack.X - 2; x <= enemyShack.X + 2; x++)
            {
                if (enemyShack.X == x && enemyShack.Y == y)
                {
                    continue;
                }

                if (GetManhattanDistance(new Point(x, y), _playerShack) <= 2)
                {
                    continue;
                }

                Point checkPoint = new Point(x, y);
                if (IsInBounds(checkPoint) && _trees.Any(t => t.Position == checkPoint))
                {
                    candidateTrees.Add(checkPoint);                    
                }
            }
        }

        // If any troll is on any candidate square, chop it
        foreach (Troll troll in _playerTrolls.Where(t => !_assigned.Contains(t.Id)))
        {
            if (candidateTrees.Any(t => t == troll.Position))
            {
                AssignTroll(troll.Id);
                return $"CHOP {troll.Id}";
            }
        }


        (Troll? closestTroll, List<Point> path) = _positionUtil.GetClosestTrollToTargets(_playerTrolls.Where(t => !_assigned.Contains(t.Id)).ToList(), candidateTrees);

        if (closestTroll != null && path.Count > 0)
        {
            Logger.Message($"Moving troll {closestTroll.Id} towards enemy for attack with next move {path[0]}");
            AssignTroll(closestTroll.Id);
            return $"MOVE {closestTroll.Id} {path[path.Count-1].X} {path[path.Count - 1].Y}";
        }

        return string.Empty;
    }

    private int GetManhattanDistance(Point point1, Point point2)
    {
        return Math.Abs(point1.X - point2.X) + Math.Abs(point1.Y - point2.Y);
    }

    private string CanWeGetIt(List<Troll> candidateTrolls, List<Point> candidatePoints, Need need)
    {
        foreach (Troll troll in candidateTrolls)
        {
            if (need == Need.HarvestIron)
            {
                foreach (Point ironSpot in candidatePoints)
                {
                    if (_positionUtil.IsAdjacentTo(troll.Position, ironSpot))
                    {
                        AssignTroll(troll.Id);
                        return $"MINE {troll.Id}";                        
                    }
                }
            }
            else
            {
                foreach (Point point in candidatePoints)
                {
                    if (troll.Position == point)
                    {
                        AssignTroll(troll.Id);
                        return $"HARVEST {troll.Id}";                        
                    }
                }
            }
        }

        return string.Empty;
    }

    private (Troll? closestTroll, Point nextMove) GetClosestTrollMove(Inventory usableInventory, ResourceType fruitType)
    {
        Troll? closestTroll = null;
        Point nextMove = new Point(-1, -1);
        List<Point> closestPath = new List<Point>();

        var eligibleTrolls = _playerTrolls.Where(t => !_assigned.Contains(t.Id) && t.CanCarry()).ToList();

        if (eligibleTrolls.Count == 0)
        {
            return (null, nextMove);
        }

        if (InventoryUtil.DoesContainFruit(usableInventory, fruitType))
        {
            // If a troll is on the shack use that
            closestTroll = eligibleTrolls.FirstOrDefault(t => t.Position == _playerShack || _positionUtil.IsAdjacentToShack(t.Position));

            if (closestTroll != null)
            {
                AssignTroll(closestTroll.Id);
                return (closestTroll, closestTroll.Position);
            }

            (closestTroll, closestPath) = _positionUtil.GetClosestTrollToTarget(eligibleTrolls, _playerShack);

            if (closestTroll.Position == _playerShack || _positionUtil.IsAdjacentToShack(closestTroll.Position) || closestPath.Count == 0)
            {
                nextMove = closestTroll.Position;
            }
            else
            {
                nextMove = closestPath[0];

            }
        }

        // TODO:
        // Get all harvestable trees of this type
        // List<Tree> harvestableTrees = _trees.Where(t => t.Type == fruitType && t.Fruits > 0).ToList();

        return (closestTroll, nextMove);
    }

    private void AssignTroll(int id)
    {
        Logger.Message($"Assigning troll {id} to a need");
        _assigned.Add(id);
    }

    private void SetAllTrollsToUnassigned()
    {
        _assigned.Clear();
    }

    private bool IsAtTree(Point position, List<Tree> trees)
    {
        return trees.Any(tree => tree.Position == position);
    }

    private bool IsNextToShack(Point position)
    {
        if (CalculationUtil.GetManhattanDistance(position, _playerShack) == 1)
        {
            return true;
        }
        
        return false;
    }

    private List<Point> GetShortestPathToShack(Point position)
    {
        List<Point> path = _positionUtil.GetShortestPath(position, _playerShack);
       
        return path;
    }

    private List<Point> GetPathToClosestTree(Point position, List<Tree> treesWithFruit, List<Point> excludedTrees)
    {
        int closestDistance = int.MaxValue;
        List<Point> closestPath = new List<Point>();

        foreach (Tree tree in treesWithFruit)
        {
            if (excludedTrees.Contains(tree.Position))
            {
                continue;
            }

            List<Point> path = _positionUtil.GetShortestPath(position, tree.Position);

            //Logger.Path($"Tree {tree.Position}", path);

            if (path.Count < closestDistance)
            {
                closestDistance = path.Count;
                closestPath = path;
            }
        }

        return closestPath;
    }

    internal void SetPlayerShack(int x, int y)
    {
        _playerShack = new Point(x, y);
    }

    internal void SetEnemyShack(int x, int y)
    {
        _enemyShack = new Point(x, y);
    }

    internal void SetEnemyInventory(Inventory inventory)
    {
        _enemyInventory = inventory;
    }

    internal void SetPlayerInventory(Inventory inventory)
    {
        _playerInventory = inventory;
    }

    internal void ClearTrees()
    {
        _trees.Clear();
    }

    internal void AddTree(Tree tree)
    {
        _trees.Add(tree);
    }

    internal void ClearTrolls()
    {
        _playerTrolls.Clear();
        _enemyTrolls.Clear();
    }

    internal int GetPlayerTrollCount()
    {
        return _playerTrolls.Count;
    }

    internal List<Tree> GetTrees(ResourceType fruitType)
    {
        return _trees.Where(tree => tree.Type == fruitType).ToList();
    }

    internal Point GetPlayerShackPosition()
    {
        return _playerShack;
    }

    internal void AddOrUpdateTroll(
        int id, 
        int player, 
        Point position, 
        int movementSpeed, 
        int carryCapacity, 
        int harvestPower, 
        int chopPower, 
        int carryPlum, 
        int carryLemon, 
        int carryApple, 
        int carryBanana, 
        int carryIron, 
        int carryWood)
    {
        if (player == 0)
        {
            if (_playerTrolls.Any(t => t.Id == id))
            {
                var troll = _playerTrolls.First(t => t.Id == id);
                troll.CarryPlum = carryPlum;
                troll.CarryLemon = carryLemon;
                troll.CarryApple = carryApple;
                troll.CarryBanana = carryBanana;
                troll.CarryWood = carryWood;
                troll.CarryIron = carryIron;
            }
            else
            {
                Troll troll = new Troll(id, position, movementSpeed, carryCapacity, harvestPower, chopPower);
                troll.CarryPlum = carryPlum;
                troll.CarryLemon = carryLemon;
                troll.CarryApple = carryApple;
                troll.CarryBanana = carryBanana;
                troll.CarryWood = carryWood;
                troll.CarryIron = carryIron;

                _playerTrolls.Add(troll);
            }
        }
        else
        {
            if (_enemyTrolls.Any(t => t.Id == id))
            {
                var troll = _enemyTrolls.First(t => t.Id == id);
                troll.CarryPlum = carryPlum;
                troll.CarryLemon = carryLemon;
                troll.CarryApple = carryApple;
                troll.CarryBanana = carryBanana;
                troll.CarryWood = carryWood;
                troll.CarryIron = carryIron;
            }
            else
            {
                Troll troll = new Troll(id, position, movementSpeed, carryCapacity, harvestPower, chopPower);
                troll.CarryPlum = carryPlum;
                troll.CarryLemon = carryLemon;
                troll.CarryApple = carryApple;
                troll.CarryBanana = carryBanana;
                troll.CarryWood = carryWood;
                troll.CarryIron = carryIron;
                _enemyTrolls.Add(troll);
            }
        }
    }

    internal bool IsInBounds(Point spot)
    {
        if(spot.X < 0 || spot.X >= _width || spot.Y < 0 || spot.Y >= _height)
        {
            return false;
        }

        return true;

    }

    internal bool IsGrowable(Point spot)
    {
        if (_isWalkable[spot.Y, spot.X] == true)
        {
            return true;
        }

        return false;
    }

    internal void SetIsWalkable(int x, int y, bool isWalkable)
    {
        _isWalkable[y, x] = isWalkable;
    }

    internal void SetIsWater(int x, int y, bool isWater)
    {
        _isWater[y, x] = isWater;
    }

    internal bool IsWater(Point spot)
    {
        return _isWater[spot.Y, spot.X];
    }

    internal bool HasTree(Point growSpot)
    {
        return _trees.Any(t => t.Position == growSpot);
    }

    internal void AddIron(int x, int y)
    {
        _iron.Add(new Point(x, y));
    }

    internal Inventory GetPlayerInventory()
    {
        return _playerInventory;
    }

    internal List<Point> GetIronPositions()
    {
        return _iron;
    }

    internal List<Tree> GetTrees()
    {
        return _trees;
    }
}

internal struct Inventory
{
    internal int Plum;
    internal int Lemon;
    internal int Apple;
    internal int Banana;
    internal int Iron;
    internal int Wood;
}



internal static class InventoryUtil
{
    internal static bool DoesContainFruit(Inventory playerInventory)
    {
        return playerInventory.Plum > 0 || playerInventory.Lemon > 0 || playerInventory.Apple > 0 || playerInventory.Banana > 0;
    }

    internal static bool DoesContainFruit(Inventory inventory, ResourceType fruitType)
    {
        if (fruitType == ResourceType.PLUM)
        {
            return inventory.Plum > 0;
        }
        else if (fruitType == ResourceType.LEMON)
        {
            return inventory.Lemon > 0;
        }
        else if (fruitType == ResourceType.APPLE)
        {
            return inventory.Apple > 0;
        }
        else if (fruitType == ResourceType.BANANA)
        {
            return inventory.Banana > 0;
        }
        else if (fruitType == ResourceType.IRON)
        {
            return inventory.Iron > 0;
        }
        else if (fruitType == ResourceType.WOOD)
        {
            return inventory.Wood > 0;
        }
        else
        {
            throw new Exception("Invalid fruit type");
        }
    }

    internal static int GetCount(Inventory inventory, ResourceType fruitType)
    {
        if (fruitType == ResourceType.PLUM)
        {
            return inventory.Plum;
        }
        else if (fruitType == ResourceType.LEMON)
        {
            return inventory.Lemon;
        }
        else if (fruitType == ResourceType.APPLE)
        {
            return inventory.Apple;
        }
        else if (fruitType == ResourceType.BANANA)
        {
            return inventory.Banana;
        }
        else if (fruitType == ResourceType.IRON)
        {
            return inventory.Iron;
        }
        else if (fruitType == ResourceType.WOOD)
        {
            return inventory.Wood;
        }
        else
        {
            throw new Exception("Invalid fruit type");
        }
    }

    internal static Inventory ChangeInventory(Inventory inventory, ResourceType fruitType, int v)
    {
        if (fruitType == ResourceType.PLUM)
        {
            return new Inventory{Plum = inventory.Plum - v, Lemon = inventory.Lemon, Apple = inventory.Apple, Banana = inventory.Banana, Iron = inventory.Iron, Wood = inventory.Wood};
        }
        else if (fruitType == ResourceType.LEMON)
        {
            return new Inventory{Plum = inventory.Plum, Lemon = inventory.Lemon - v, Apple = inventory.Apple, Banana = inventory.Banana, Iron = inventory.Iron, Wood = inventory.Wood};
        }
        else if (fruitType == ResourceType.APPLE)
        {
            return new Inventory{Plum = inventory.Plum, Lemon = inventory.Lemon, Apple = inventory.Apple - v, Banana = inventory.Banana, Iron = inventory.Iron, Wood = inventory.Wood};
        }
        else if (fruitType == ResourceType.BANANA)
        {
            return new Inventory{Plum = inventory.Plum, Lemon = inventory.Lemon, Apple = inventory.Apple, Banana = inventory.Banana - v, Iron = inventory.Iron, Wood = inventory.Wood};
        }
        else if (fruitType == ResourceType.IRON)
        {
            return new Inventory{Plum = inventory.Plum, Lemon = inventory.Lemon, Apple = inventory.Apple, Banana = inventory.Banana, Iron = inventory.Iron - v, Wood = inventory.Wood};
        }
        else if (fruitType == ResourceType.WOOD)
        {
            return new Inventory{Plum = inventory.Plum, Lemon = inventory.Lemon, Apple = inventory.Apple, Banana = inventory.Banana, Iron = inventory.Iron, Wood = inventory.Wood - v};
        }
        else
        {
            throw new Exception("Invalid fruit type");
        }
    }

    internal static ResourceType GetAnyFruitType(Inventory playerInventory)
    {
        // TODO: Order by most plentiful
        if (playerInventory.Plum > 1)
        {
            return ResourceType.PLUM;
        }
        else if (playerInventory.Lemon > 1)
        {
            return ResourceType.LEMON;
        }
        else if (playerInventory.Apple > 1)
        {
            return ResourceType.APPLE;
        }
        else if (playerInventory.Banana > 1)
        {
            return ResourceType.BANANA;
        }

        return ResourceType.PLUM;
    }
}

internal static class Logger    
{
    private static bool DISABLE_LOGGING = false;
    private static bool DISABLE_TIMES = false;

    private static long _roundStartTime;
    private static long _lastTimedLog;

    internal static void Message(string message)
    {
        if (DISABLE_LOGGING)
        {
            return;
        }

        Console.Error.WriteLine(message);
    }

    internal static void DisableLogging() 
    {
        DISABLE_LOGGING = true;
    }

    internal static void EnableLogging()
    {
        DISABLE_LOGGING = false;
    }

    internal static void StartRoundStopwatch()
    {
        if (DISABLE_TIMES)
        {
            return;
        }
        _roundStartTime = Stopwatch.GetTimestamp();
        _lastTimedLog = Stopwatch.GetTimestamp();
    }

    internal static void LogTime(string message)
    {
        if (DISABLE_TIMES)
        {
            return;
        }
        TimeSpan elapsedTime = Stopwatch.GetElapsedTime(_roundStartTime);
        TimeSpan elapsedSinceLastLog = Stopwatch.GetElapsedTime(_lastTimedLog);
        Console.Error.WriteLine($"{elapsedTime.TotalMilliseconds}({elapsedSinceLastLog.TotalMilliseconds}): {message}");
        _lastTimedLog = Stopwatch.GetTimestamp();
    }

    internal static void Inventory(string message,Inventory inventory)
    {
        if (DISABLE_LOGGING)
        {
            return;
        }

        Console.Error.WriteLine(message);
        Console.Error.WriteLine($"Plum: {inventory.Plum}, Lemon: {inventory.Lemon}, Apple: {inventory.Apple}, Banana: {inventory.Banana}, Iron: {inventory.Iron}, Wood: {inventory.Wood}");
    }

    internal static void Path(string message, List<Point> path)
    {
        if (DISABLE_LOGGING)
        {
            return;
        }

        Console.Error.WriteLine(message);
        Console.Error.WriteLine($"Path: {string.Join("->", path)}");

    }

    internal static void Troll(Troll troll)
    {
        if (DISABLE_LOGGING)
        {
            return;
        }

        Console.Error.WriteLine($"Troll {troll.Id} at {troll.Position}, MovementSpeed: {troll.MovementSpeed}, CarryCapacity: {troll.CarryCapacity}, HarvestPower: {troll.HarvestPower}, ChopPower: {troll.ChopPower}, CarryPlum: {troll.CarryPlum}, CarryLemon: {troll.CarryLemon}, CarryApple: {troll.CarryApple}, CarryBanana: {troll.CarryBanana}, CarryIron: {troll.CarryIron}, CarryWood: {troll.CarryWood}");
    }

    internal static void Prioirities(List<Need> priorities)
    {
        if (DISABLE_LOGGING)
        {
            return;
        }

        Console.Error.WriteLine("PRIORITIES:");
        foreach (Need need in priorities)
        {
            Console.Error.WriteLine(need);
        }
    }

    internal static void Error(string message)
    {
        Console.Error.WriteLine($"ERROR: {message}");
    }

    internal static void Trolls(List<Troll> playerTrolls)
    {
        if (DISABLE_LOGGING)
        {
            return;
        }

        Console.Error.WriteLine("TROLLS:");
        foreach (Troll troll in playerTrolls)
        {
            Troll(troll);
        }
    }

    internal static void Trees(List<Tree> trees)
    {
        if (DISABLE_LOGGING)
        {
            return;
        }

        foreach (Tree tree in trees)
        {
            Console.Error.WriteLine($"Tree at {tree.Position}, Type: {tree.Type}, Size: {tree.Size}, Health: {tree.Health}, Fruits: {tree.Fruits}, Cooldown: {tree.Cooldown}");
        }

    }        
}

internal enum Need
{
    GrowPlum,
    GrowLemon,
    GrowApple,
    GrowBanana,
    HarvestPlum,
    HarvestLemon,
    HarvestApple,
    HarvestBanana,
    HarvestIron,
    AttackEnemy,
    HarvestEnemyWood,
    HarvestAnyWood,
    TrainTroll,
}


internal sealed class NeedsManager
{
    private const int EARLY_GAME_END = 100;
    private const int MID_GAME_END = 200;

    private readonly Game _game;
    private readonly PositionUtil _positionUtil;

    private List<Need> _priorities = new List<Need>();

    public NeedsManager(Game game, PositionUtil positionUtil)
    {
        _game = game;
        _positionUtil = positionUtil;
    }

    internal void SetPriorities()
    {
        _priorities.Clear();

        if (_game.Turn < EARLY_GAME_END || _game.Turn < MID_GAME_END)
        {

            CheckAndAddGrowPriorities();
            CheckAndAddHarvestPriorities();
            CheckAndAddHarvestPriorities(); // Add more as a fall back. No harm in harvesting more if I have a lot of trolls
            _priorities.Add(Need.AttackEnemy);
            _priorities.Add(Need.AttackEnemy);
            _priorities.Add(Need.AttackEnemy);

            _priorities.Add(Need.TrainTroll);
        }
        else
        {
            _priorities.Add(Need.HarvestAnyWood);
            _priorities.Add(Need.HarvestAnyWood);
            _priorities.Add(Need.HarvestAnyWood);
            _priorities.Add(Need.HarvestAnyWood);
            _priorities.Add(Need.HarvestAnyWood);
            _priorities.Add(Need.HarvestAnyWood);
            _priorities.Add(Need.HarvestAnyWood);
            _priorities.Add(Need.HarvestAnyWood);
        }
    }

    private void CheckAndAddHarvestPriorities()
    {
        Logger.Inventory("Player inventory", _game.GetPlayerInventory());
        List<(int, ResourceType)> priorities = new List<(int, ResourceType)>();

        int plumCount = InventoryUtil.GetCount(_game.GetPlayerInventory(), ResourceType.PLUM);
        priorities.Add((plumCount, ResourceType.PLUM));

        int lemonCount = InventoryUtil.GetCount(_game.GetPlayerInventory(), ResourceType.LEMON);
        priorities.Add((lemonCount, ResourceType.LEMON));

        int appleCount = InventoryUtil.GetCount(_game.GetPlayerInventory(), ResourceType.APPLE);
        priorities.Add((appleCount, ResourceType.APPLE));

        int bananaCount = InventoryUtil.GetCount(_game.GetPlayerInventory(), ResourceType.BANANA);
        priorities.Add((bananaCount, ResourceType.BANANA));

        // Don't prioritise iron if we have 4 trolls. We'll still add it, just as a much lower priority later
        if (_game.GetPlayerInventory().Iron < 10 && _game.GetPlayerTrollCount() < 4)
        {
            int ironCount = InventoryUtil.GetCount(_game.GetPlayerInventory(), ResourceType.IRON);
            priorities.Add((ironCount, ResourceType.IRON));
        }

        priorities.Sort((a, b) => a.Item1.CompareTo(b.Item1));

        foreach ((int count, ResourceType type) in priorities)
        {
            if (type == ResourceType.PLUM)
            {
                _priorities.Add(Need.HarvestPlum);
            }
            else if (type == ResourceType.LEMON)
            {
                _priorities.Add(Need.HarvestLemon);
            }
            else if (type == ResourceType.APPLE)
            {
                _priorities.Add(Need.HarvestApple);
            }
            else if (type == ResourceType.BANANA)
            {
                _priorities.Add(Need.HarvestBanana);
            }
            else if (type == ResourceType.IRON)
            {
                _priorities.Add(Need.HarvestIron);
            }
        }
    }

    private void CheckAndAddGrowPriorities()
    {
        int neededDist = 3;

        List<(int, ResourceType)> priorities = new List<(int, ResourceType)>();

        // Number of trees within 3 of shack
        int plumTreeCount = TreeCountWithinDistOfShack(ResourceType.PLUM, neededDist);
        int lemonTreeCount = TreeCountWithinDistOfShack(ResourceType.LEMON, neededDist);
        int appleTreeCount = TreeCountWithinDistOfShack(ResourceType.APPLE, neededDist);
        int bananaTreeCount = TreeCountWithinDistOfShack(ResourceType.BANANA, neededDist);

        // Number of fruit in inventory
        int plumCount = InventoryUtil.GetCount(_game.GetPlayerInventory(), ResourceType.PLUM);
        int lemonCount = InventoryUtil.GetCount(_game.GetPlayerInventory(), ResourceType.LEMON);
        int appleCount = InventoryUtil.GetCount(_game.GetPlayerInventory(), ResourceType.APPLE);
        int bananaCount = InventoryUtil.GetCount(_game.GetPlayerInventory(), ResourceType.BANANA);

        int plumPriority = CalculatePriority(plumCount, plumTreeCount);
        int lemonPriority = CalculatePriority(lemonCount, lemonTreeCount);
        int applePriority = CalculatePriority(appleCount, appleTreeCount);
        int bananaPriority = CalculatePriority(bananaCount, bananaTreeCount);

        Logger.Message($"Grow priorities - Plum: {plumPriority} (Count: {plumCount}, Trees: {plumTreeCount}), Lemon: {lemonPriority} (Count: {lemonCount}, Trees: {lemonTreeCount}), Apple: {applePriority} (Count: {appleCount}, Trees: {appleTreeCount}), Banana: {bananaPriority} (Count: {bananaCount}, Trees: {bananaTreeCount})");
        if (plumPriority > 0)
        {
            priorities.Add((plumPriority, ResourceType.PLUM));
        }

        if(lemonPriority > 0)
        { 
            priorities.Add((lemonPriority, ResourceType.LEMON));
        }

        if(applePriority > 0)
        {
            priorities.Add((applePriority, ResourceType.APPLE));
        }

        if(bananaPriority > 0)
        {
            priorities.Add((bananaPriority, ResourceType.BANANA));
        }             

        priorities.Sort((a, b) => b.Item1.CompareTo(a.Item1));

        foreach ((int count, ResourceType type) in priorities)
        {
            if (type == ResourceType.PLUM)
            {
                _priorities.Add(Need.GrowPlum);
            }
            else if (type == ResourceType.LEMON)
            {
                _priorities.Add(Need.GrowLemon);
            }
            else if (type == ResourceType.APPLE)
            {
                _priorities.Add(Need.GrowApple);
            }
            else if (type == ResourceType.BANANA)
            {
                _priorities.Add(Need.GrowBanana);
            }
        }
    }

    private int CalculatePriority(int inventoryCount, int treeCount)
    {
        int priority = -1;
        
        if (treeCount == 0)
        {
            priority += 100;
        }
        else if (treeCount == 1)
        {
            priority += 50;
        }
        

        // We want ones with a smaller inventory to be prioritised
        if (priority >= 0)
        {
            priority += (40 - inventoryCount);
        }

        return priority;
    }

    private int TreeCountWithinDistOfShack(int neededDist)
    {
        int count = 0;

        foreach (Tree tree in _game.GetTrees().OrderBy(t => _positionUtil.CalculateManhattanDistance(_game.GetPlayerShackPosition(), t.Position)).ToList())
        {
            if (_positionUtil.CalculateManhattanDistance(_game.GetPlayerShackPosition(), tree.Position) > neededDist)
            {
                continue;
            }

            if (_positionUtil.GetShortestPath(_game.GetPlayerShackPosition(), tree.Position).Count <= neededDist)
            {
                count++;
            }
        }

        return count;
    }

    private int TreeCountWithinDistOfShack(ResourceType fruitType, int neededDist)
    {
        List<Tree> eligibleTrees = _game.GetTrees(fruitType);

        eligibleTrees = eligibleTrees.OrderBy(t => _positionUtil.CalculateManhattanDistance(_game.GetPlayerShackPosition(), t.Position)).ToList();

        int count = 0;
         
        foreach (Tree tree in eligibleTrees)
        {
            if (_positionUtil.CalculateManhattanDistance(_game.GetPlayerShackPosition(), tree.Position) > neededDist)
            {
                continue;
            }
                
            if(_positionUtil.GetShortestPath(_game.GetPlayerShackPosition(), tree.Position).Count <= neededDist)
            {
                count++;
            }
        }

        return count;
    }

    internal List<Need> GetPriorities()
    {
        return _priorities;
    }

    internal static bool IsGrowNeed(Need need)
    {
        return need == Need.GrowPlum || need == Need.GrowLemon || need == Need.GrowApple || need == Need.GrowBanana;
    }

    internal static ResourceType GetTreeType(Need need)
    {
        switch (need)
        {
            case Need.GrowPlum:
            case Need.HarvestPlum:
                return ResourceType.PLUM;
            case Need.GrowLemon:
            case Need.HarvestLemon:
                return ResourceType.LEMON;
            case Need.GrowApple:
            case Need.HarvestApple:
                return ResourceType.APPLE;
            case Need.GrowBanana:
            case Need.HarvestBanana:
                return ResourceType.BANANA;
            case Need.HarvestIron:
                return ResourceType.IRON;
            case Need.HarvestEnemyWood:
            case Need.HarvestAnyWood:
                return ResourceType.WOOD;
            default:
                return ResourceType.UNKNOWN;
        }
    }

    internal static bool IsharvestNeed(Need need)
    {
        return need == Need.HarvestPlum || need == Need.HarvestLemon || need == Need.HarvestApple || need == Need.HarvestBanana || need == Need.HarvestIron || need == Need.HarvestEnemyWood || need == Need.HarvestAnyWood;
    }
}


internal sealed class Node
{
    internal Point Position { get; set; }

    internal Node? Parent { get; set; }

    internal int G { get; set; }
    internal int H { get; set; }
    internal int F { get; set; }

    internal bool Closed { get; set; }

    internal Node(Point position)
    {
        Position = position;
    }
}


internal sealed class PathFinder
{
    private readonly int _width;
    private readonly int _height;
    private readonly bool[,] _isWalkable;

    internal PathFinder(int width, int height, bool[,] isWalkable)
    {
        _width = width;
        _height = height;

        _isWalkable = isWalkable;
    }

    internal List<Point> GetShortestPath(Point startPosition, Point targetPosition)
    {
        var nodes = new List<Node>();
        var currentNode = new Node(startPosition);
        currentNode.H = CalculationUtil.GetManhattanDistance(startPosition, targetPosition);
        nodes.Add(currentNode);

        bool targetFound = false;

        while (targetFound == false && nodes.Where(n => n.Closed == false).Any())
        {
            List<Point> pointsToCheck = GetPointsToCheck(currentNode);

            foreach (Point pointToCheck in pointsToCheck)
            {
                if (pointToCheck == currentNode.Position || ((!_isWalkable[pointToCheck.Y, pointToCheck.X]) && pointToCheck != targetPosition))
                {
                    continue;
                }

                Node? existingNode = nodes.SingleOrDefault(n => n.Position == pointToCheck);

                if (existingNode == null)
                {
                    Node node = new Node(pointToCheck);

                    node.Parent = currentNode;

                    node.G = currentNode.G + 1;

                    node.H = CalculationUtil.GetManhattanDistance(pointToCheck, targetPosition);
                    node.F = node.G + node.H;

                    nodes.Add(node);
                    
                }
                else
                {
                    if (!existingNode.Closed)
                    {
                        int g = currentNode.G + 1;

                        if (g < existingNode.G)
                        {
                            existingNode.G = g;

                            existingNode.F = existingNode.G + existingNode.H;

                            existingNode.Parent = currentNode;
                        }
                    }
                }
            }

            currentNode.Closed = true;

            if (currentNode.Position == targetPosition)
            {
                targetFound = true;
            }
            else
            {
                nodes = nodes.OrderBy(n => n.Closed == true).ThenBy(n => n.F).ToList();
                currentNode = nodes.First();
            }
        }

        if (targetFound)
        {
            List<Point> shortestPath = new List<Point>();
            while (currentNode != null)
            {
                if (currentNode.Position != startPosition)
                {
                    shortestPath.Add(currentNode.Position);
                }
                currentNode = currentNode.Parent;
            }
            shortestPath.Reverse();            
            return shortestPath;
        }

        // No path found
        return new List<Point>();
    }

    private List<Point> GetPointsToCheck(Node currentNode)
    {
        List<Point> pointsToCheck = new List<Point>();

        if (currentNode.Position.X + 1 < _width)
        {
            pointsToCheck.Add(new Point(currentNode.Position.X + 1, currentNode.Position.Y));
        }

        if (currentNode.Position.X - 1 >= 0)
        {
            pointsToCheck.Add(new Point(currentNode.Position.X - 1, currentNode.Position.Y));
        }

        if (currentNode.Position.Y + 1 < _height)
        {
            pointsToCheck.Add(new Point(currentNode.Position.X, currentNode.Position.Y + 1));
        }

        if (currentNode.Position.Y - 1 >= 0)
        {
            pointsToCheck.Add(new Point(currentNode.Position.X, currentNode.Position.Y - 1));
        }

        if (pointsToCheck.Count == 0)
        {
            Console.Error.WriteLine("ERROR: No points to check from current node");
        }

        return pointsToCheck;
    }
}




partial class Player
{
    static void Main(string[] args)
    {
        string[] inputs;
        inputs = Console.ReadLine().Split(' ');
        int width = int.Parse(inputs[0]);
        int height = int.Parse(inputs[1]);

        Game game = new Game(width, height);

        for (int y = 0; y < height; y++)
        {
            string line = Console.ReadLine();

            Logger.Message(line);

            char[] rowText = line.ToCharArray();


            for (int x = 0; x < width; x++)
            {
                if(rowText[x] == '.')
                {
                    game.SetIsWalkable(x, y, true);
                }
                else if (rowText[x] == '~')
                {
                    game.SetIsWater(x, y, true);
                }
                else if (rowText[x] == '+')
                {
                    game.AddIron(x, y);
                }
                else if (rowText[x] == '0')
                {
                    game.SetPlayerShack(x, y);
                }
                else if (rowText[x] == '1')
                {
                    game.SetEnemyShack(x, y);
                }
            }
        }

        game.Initialise();

        // game loop
        while (true)
        {
            game.ClearTrees();
            game.ClearTrolls();

            for (int i = 0; i < 2; i++)
            {
                inputs = Console.ReadLine().Split(' ');
                int plum = int.Parse(inputs[0]);
                int lemon = int.Parse(inputs[1]);
                int apple = int.Parse(inputs[2]);
                int banana = int.Parse(inputs[3]);
                int iron = int.Parse(inputs[4]);
                int wood = int.Parse(inputs[5]);

                if (i == 0)
                {
                    game.SetPlayerInventory(new Inventory
                    {
                        Plum = plum,
                        Lemon = lemon,
                        Apple = apple,
                        Banana = banana,
                        Iron = iron,
                        Wood = wood
                    });
                }
                else
                {
                    game.SetEnemyInventory(new Inventory
                    {
                        Plum = plum,
                        Lemon = lemon,
                        Apple = apple,
                        Banana = banana,
                        Iron = iron,
                        Wood = wood
                    });
                }
            }

            int treesCount = int.Parse(Console.ReadLine());
            for (int i = 0; i < treesCount; i++)
            {
                inputs = Console.ReadLine().Split(' ');
                string type = inputs[0];
                int x = int.Parse(inputs[1]);
                int y = int.Parse(inputs[2]);
                int size = int.Parse(inputs[3]);
                int health = int.Parse(inputs[4]);
                int fruits = int.Parse(inputs[5]);
                int cooldown = int.Parse(inputs[6]);

                game.AddTree(new Tree
                {
                    Type = Enum.Parse<ResourceType>(type, true),
                    Position = new Point(x, y),
                    Size = size,
                    Health = health,
                    Fruits = fruits,
                    Cooldown = cooldown
                });
            }


            int trollsCount = int.Parse(Console.ReadLine());
            for (int i = 0; i < trollsCount; i++)
            {
                inputs = Console.ReadLine().Split(' ');
                int id = int.Parse(inputs[0]);
                int player = int.Parse(inputs[1]);
                int x = int.Parse(inputs[2]);
                int y = int.Parse(inputs[3]);
                int movementSpeed = int.Parse(inputs[4]);
                int carryCapacity = int.Parse(inputs[5]);
                int harvestPower = int.Parse(inputs[6]);
                int chopPower = int.Parse(inputs[7]);
                int carryPlum = int.Parse(inputs[8]);
                int carryLemon = int.Parse(inputs[9]);
                int carryApple = int.Parse(inputs[10]);
                int carryBanana = int.Parse(inputs[11]);
                int carryIron = int.Parse(inputs[12]);
                int carryWood = int.Parse(inputs[13]);

                game.AddOrUpdateTroll(id, 
                                      player, 
                                      new Point(x, y), 
                                      movementSpeed, 
                                      carryCapacity, 
                                      harvestPower, 
                                      chopPower,
                                      carryPlum, 
                                      carryLemon, 
                                      carryApple, 
                                      carryBanana, 
                                      carryIron, 
                                      carryWood);
            }

            // Write an action using Console.WriteLine()
            // To debug: Console.Error.WriteLine("Debug messages...");

            // valid actions:
            // MOVE <id> <x> <y>
            // HARVEST <id> - when you are on the same cell as a tree
            // DROP <id> - when you are next to your shack and carry items
            string actions = string.Join(";", game.GetActions());

            Console.WriteLine(actions);

            // Console.WriteLine("MOVE 0 7 7");
        }
    }
}


internal class PositionUtil
{
    private readonly Game _game;
    private readonly PathFinder _pathFinder;

    private List<Point> _bestGrowSpots = new List<Point>();

    public PositionUtil(Game game, PathFinder pathFinder)
    {
        _game = game;
        _pathFinder = pathFinder;
    }

    internal List<Point> GetShortestPath(Point startPos, Point endPos)
    {
        return _pathFinder.GetShortestPath(startPos, endPos);
    }

    internal int GetClosestTreeToShack(ResourceType fruitType)
    {
        List<Tree> treesOfCorrectType = _game.GetTrees(fruitType);

        int closest = int.MaxValue;

        foreach (Tree tree in treesOfCorrectType)
        {
            int dist = _pathFinder.GetShortestPath(_game.GetPlayerShackPosition(), tree.Position).Count;
            if (dist < closest)
            {
                closest = dist;
            }
        }

        return closest;
    }

    internal void InitialiseBestGrowSpots()
    {
        const int MIN_DIST = 3;
        Point shackPos = _game.GetPlayerShackPosition();

        Logger.Message($"Initialising best grow spots around shack at {shackPos.X}, {shackPos.Y}");

        List<Point> validSpots = new List<Point>();

        for (int x = shackPos.X - 3; x <= shackPos.X + 3; x++)
        {
            for (int y = shackPos.Y - 3; y <= shackPos.Y + 3; y++)
            {
                if (x == shackPos.X && y == shackPos.Y)
                {
                    continue; // Skip the shack position itself
                }

                Point checkPoint = new Point(x, y);
                if (_game.IsInBounds(checkPoint) && _game.IsGrowable(checkPoint))
                {
                    validSpots.Add(checkPoint);
                }
            }
        }   

        // order valid spots by pathfinder distance to shack
        List<(int,Point)> distancesMap = new List<(int, Point)>();

        foreach (Point spot in validSpots)
        {
            int dist = _pathFinder.GetShortestPath(shackPos, spot).Count;

            if (dist <= MIN_DIST)
            distancesMap.Add((dist, spot));
        }

        // Order so that all spots adjacent to water are first (ordered by closest to shack), then order the rest by closerst to sack
        // This is because we want to prioritise growing trees adjacent to water, but if there are none available, we want to grow trees as close to the shack as possible
        _bestGrowSpots = distancesMap.OrderByDescending(d => IsAdjacentToWater(d.Item2)).ThenBy(d => d.Item1).Select(d => d.Item2).ToList();

        foreach (Point spot in _bestGrowSpots)
        {
            Console.Error.WriteLine($"Best grow spot: {spot.X}, {spot.Y}");
        }
    }

    private bool IsAdjacentToWater(Point point)
    {
        List<Point> adjacentPoints = new List<Point>
        {
            new Point(point.X - 1, point.Y),
            new Point(point.X + 1, point.Y),
            new Point(point.X, point.Y - 1),
            new Point(point.X, point.Y + 1)
        };

        return adjacentPoints.Any(p => _game.IsInBounds(p) && _game.IsWater(p));
    }

    internal (Troll? closestTroll, List<Point> shortestPath) GetClosestTrollToTargets(List<Troll> candidateTrolls, List<Point> candidatePoints, int cutoff = int.MaxValue)
    {
        int closestDistance = int.MaxValue;
        Troll? closestTroll = null;
        List<Point> pathToTarget = new List<Point>();

        foreach (Point tree in candidatePoints)
        {
            (Troll? troll, List<Point> path) = GetClosestTrollToTarget(candidateTrolls, tree, Math.Min(closestDistance, cutoff));

            if (path.Count < closestDistance)
            {
                closestDistance = path.Count;
                closestTroll = troll;
                pathToTarget = path;
            }
        }
        
        return (closestTroll, pathToTarget);
    }

    internal (Troll?, List<Point>)  GetClosestTrollToTarget(List<Troll> trolls, Point target, int cutoff = int.MaxValue)
    {
        int closestDistance = int.MaxValue;
        Troll? closestTroll = null;
        List<Point> pathToTarget = new List<Point>();

        // Order trolls by closest manhattan distance to target first
        trolls = trolls.OrderBy(t => CalculateManhattanDistance(t.Position, target)).ToList();

        foreach (Troll troll in trolls)
        {
            Logger.Message($"Checking troll {troll.Id} at position {troll.Position.X}, {troll.Position.Y} for target at {target.X}, {target.Y}");
            if (troll.Position == target)
            {
                return (troll, new List<Point> { troll.Position });
            }

            if (closestTroll != null && (CalculateManhattanDistance(troll.Position, target) >= closestDistance || CalculateManhattanDistance(troll.Position, target) >= cutoff))
            {
                Logger.Message($"Cut OFF: Troll {closestTroll.Id}");
                return (closestTroll, pathToTarget);
            }

            Logger.Message($"Calculating path from troll {troll.Id} at {troll.Position.X}, {troll.Position.Y} to target at {target.X}, {target.Y}");
            List<Point> path = _pathFinder.GetShortestPath(troll.Position, target);
            Logger.Message($"Path length: {path.Count}");

            if (path.Count < closestDistance)
            {
                Logger.Message($"New closest troll {troll.Id} at {troll.Position.X}, {troll.Position.Y} with path length {path.Count}");
                closestDistance = path.Count;
                closestTroll = troll;
                pathToTarget = path;
            }
        }

        Logger.Message($"Closest troll to target at {target.X}, {target.Y} is troll {closestTroll?.Id} with path length {closestDistance}");

        return (closestTroll, pathToTarget);
    }

    internal int CalculateManhattanDistance(Point position1, Point position2)
    {
        return Math.Abs(position1.X - position2.X) + Math.Abs(position1.Y - position2.Y);
    }

    internal bool IsTreeAtPosition(Point position, ResourceType fruitType)
    {
        return _game.GetTrees(fruitType).Any(t => t.Position == position);
    }

    internal Point GetBestGrowSpot()
    {

        // TODO: Order by closest to current position (and next to water)
        foreach (Point growSpot in _bestGrowSpots)
        {
            if (!_game.HasTree(growSpot))
            {
                return growSpot;
            }
        }
            
        Logger.Error("No valid grow spots found!");
        return new Point(-1, -1);
    }

    internal bool IsAdjacentToShack(Point position)
    {
        Point shackPos = _game.GetPlayerShackPosition();
        List<Point> adjacentPoints = new List<Point>
        {
            new Point(shackPos.X - 1, shackPos.Y),
            new Point(shackPos.X + 1, shackPos.Y),
            new Point(shackPos.X, shackPos.Y - 1),
            new Point(shackPos.X, shackPos.Y + 1)
        };
        return adjacentPoints.Any(p => p == position);
    }

    internal bool IsAdjacentTo(Point position, Point target)
    {
        List<Point> adjacentPoints = new List<Point>
        {
            new Point(target.X - 1, target.Y),
            new Point(target.X + 1, target.Y),
            new Point(target.X, target.Y - 1),
            new Point(target.X, target.Y + 1)
        };
        return adjacentPoints.Any(p => p == position);
    }

    internal int ShackToIronDistance()
    {
        List<Point> ironPositions = _game.GetIronPositions();

        // Order by manhattan distance to player shack first, then get pathfinder distance to closest one
        ironPositions = ironPositions.OrderBy(p => CalculateManhattanDistance(p, _game.GetPlayerShackPosition())).ToList();

        int closestDistance = int.MaxValue;

        foreach (Point ironPos in ironPositions)
        {
            if (CalculateManhattanDistance(ironPos, _game.GetPlayerShackPosition()) >= closestDistance)
            {
                continue;
            }

            List<Point> path = _pathFinder.GetShortestPath(_game.GetPlayerShackPosition(), ironPos);

            if (path.Count < closestDistance)
            {
                closestDistance = path.Count;
            }
        }

        return closestDistance;
    }

    internal Point GetClosestGrowableSpot(Point position)
    {
        List<Point> growableSpots = new List<Point>();
        for (int x = position.X - 3; x <= position.X + 3; x++)
        {
            for (int y = position.Y - 3; y <= position.Y + 3; y++)
            {
                Point checkPoint = new Point(x, y);
                if (_game.IsInBounds(checkPoint) 
                    && _game.IsGrowable(checkPoint)
                    && !_game.HasTree(checkPoint)
                    )
                {
                    growableSpots.Add(checkPoint);
                }
            }
        }

        Point closestSpot = new Point(-1, -1);
        int closestDistance = int.MaxValue;
        foreach (Point spot in growableSpots)
        {
            int dist = _pathFinder.GetShortestPath(position, spot).Count;
            if (dist < closestDistance)
            {
                closestDistance = dist;
                closestSpot = spot;
            }
        }
        return closestSpot;

    }
}


internal enum ResourceType
{
    PLUM,
    LEMON,
    APPLE,
    BANANA,
    IRON,
    WOOD,
    UNKNOWN
}



internal static class TrainingUtil
{
    internal static (int plums, int lemons, int apples, int iron) GetBestTrollTraining(int numberOfTrolls, Inventory inventory)
    {
        int plums = GetMaxAmount(numberOfTrolls, inventory.Plum);
        int lemons = GetMaxAmount(numberOfTrolls, inventory.Lemon);
        int apples = GetMaxAmount(numberOfTrolls, inventory.Apple);
        int iron = GetMaxAmount(numberOfTrolls, inventory.Iron);

        return (plums, lemons, apples, iron);
    }

    private static int GetMaxAmount(int numberOfTrolls, int fruitCount)
    {
        int minimumRequired = numberOfTrolls + 1;

        if (minimumRequired > fruitCount)
        {
            // We can't do it!
            return 0;
        }

        int lastbaseStat = 1;
        int lastValid = numberOfTrolls + lastbaseStat;

        while (true)
        {
            lastbaseStat++;

            int required = numberOfTrolls + (lastbaseStat * lastbaseStat);

            if (required <= fruitCount)
            {
                lastValid = required;
            }
            else
            {
                break;
            }

        }

        return lastbaseStat-1;
    }
}



internal struct Tree
{
    internal ResourceType Type;
    internal Point Position;
    internal int Size;
    internal int Health;
    internal int Fruits;
    internal int Cooldown;
}

internal class Troll
{
    internal int Id { get; private set; }
    internal Point Position { get; private set; }
    internal int MovementSpeed { get; private set; }
    internal int CarryCapacity { get; private set; }
    internal int HarvestPower { get; private set; }

    internal int ChopPower { get; set; }
    internal int CarryPlum { get; set; }
    internal int CarryLemon { get; set; }
    internal int CarryApple { get; set; }
    internal int CarryBanana { get; set; }
    internal int CarryIron { get; set; }
    internal int CarryWood { get; set; }

    public Troll(int id, Point position, int movementSpeed, int carryCapacity, int harvestPower, int chopPower)
    {
        Id = id;
        Position = position;
        MovementSpeed = movementSpeed;
        CarryCapacity = carryCapacity;
        HarvestPower = harvestPower;
        ChopPower = chopPower;
    }

    internal int GetTotalCarrying()
    {
        return CarryPlum + CarryLemon + CarryApple + CarryBanana + CarryIron + CarryWood;
    }

    internal bool IsCarryingAnyFruit()
    {
        return CarryPlum > 0 || CarryLemon > 0 || CarryApple > 0 || CarryBanana > 0;
    }


    internal int IsCarryingFruit(ResourceType fruitType)
    {
        if (fruitType == ResourceType.PLUM)
        {
            return CarryPlum;
        }
        else if (fruitType == ResourceType.LEMON)
        {
            return CarryLemon;
        }
        else if (fruitType == ResourceType.APPLE)
        {
            return CarryApple;
        }
        else if (fruitType == ResourceType.BANANA)
        {
            return CarryBanana;
        }
        else if (fruitType == ResourceType.IRON)
        {
            return CarryIron;
        }
        else if (fruitType == ResourceType.WOOD)
        {
            return CarryWood;
        }
        else
        {
            return 0;
        }
    }

    internal bool CanCarry()
    {
        return GetTotalCarrying() < CarryCapacity;
    }

    internal ResourceType CarryingFruitType()
    {
        if (CarryPlum > 0)
        {
            return ResourceType.PLUM;
        }
        else if (CarryLemon > 0)
        {
            return ResourceType.LEMON;
        }
        else if (CarryApple > 0)
        {
            return ResourceType.APPLE;
        }
        else if (CarryBanana > 0)
        {
            return ResourceType.BANANA;
        }

        return ResourceType.PLUM;
    }

    internal bool IsCarryingWood()
    {
        return CarryWood > 0;
    }
}
    

