/**************************************************************
  This file was generated by FileConcatenator.
  It combined all classes in the project to work in Codingame.
***************************************************************/

using System.Drawing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Diagnostics;
using System.Text;
using System.Threading;
using System.IO;
using System.Collections;
using System.Runtime.CompilerServices;

internal class Creature
{
    internal int Id { get; private set; }
    internal int Color { get; private set; }
    internal int Type { get; private set; }

    internal bool IsVisible { get; set; }
    internal Point Position { get; set; }
    internal Point Velocity { get; set; }

    internal int LastSeenRound { get; set; }

    internal Creature(int id, int color, int type)
    {
        Id = id;
        Color = color;
        Type = type;
    }
}


internal enum CreatureDirection
{
    TL,
    TR,
    BL,
    BR
}

internal class DirectionCalculator
{
    private Game game;

    public DirectionCalculator(Game game)
    {
        this.game = game;
    }

    internal CreatureDirection GetBestDirectionFromRadarBlips(Drone drone)
    {
        // First pass
        // Just go in the direction with the most creatures
        Dictionary<CreatureDirection, int> directionCounts = new Dictionary<CreatureDirection, int>();

        foreach (var direction in drone.CreatureDirections)
        {
            var incrementAmount = 0;

            // If a creature has been scanned/stored by me don't count it
            if (game.MyStoredCreatureIds.Contains(direction.Key) || drone.ScannedCreaturesIds.Contains(direction.Key))
            {
                incrementAmount = 0;
            }
            else if (!game.MyStoredCreatureIds.Contains(direction.Key) && !game.IsScannedByMe(direction.Key))
            {
                incrementAmount = 1;
            }           

            if (directionCounts.ContainsKey(direction.Value))
            {
                directionCounts[direction.Value] += incrementAmount;
            }
            else
            {
                directionCounts[direction.Value] = incrementAmount;
            }
        }

        // return the key with the highest value
        Console.Error.WriteLine($"Direction Counts: {string.Join(", ", directionCounts.Select(dc => $"{dc.Key}: {dc.Value}"))}");
        return directionCounts.MaxBy(dc => dc.Value).Key;
         
    }
}

internal static class DistanceCalculator
{
    internal static int GetDistance(Point position1, Point position2)
    {
        var dx = position1.X - position2.X;
        var dy = position1.Y - position2.Y;
        return (int)Math.Sqrt(dx * dx + dy * dy);
    }

    internal static Point GetPointAlongPath(Point position, Point target, int droneSpeed)
    {
        var dx = target.X - position.X;
        var dy = target.Y - position.Y;
        var distance = Math.Sqrt(dx * dx + dy * dy);
        if (distance == 0)
        {
            return position; // Already at the target
        }
        var ratio = droneSpeed / distance;
        var newX = (int)(position.X + dx * ratio);
        var newY = (int)(position.Y + dy * ratio);
        return new Point(newX, newY);
    }

    // Determines whether two objects, each moving along a linear path at their own speed,
    // will ever be within a given proximity (default 500 units) of each other during their movement.
    // Returns true if at any point during one step of movement the two entities are within proximityThreshold units.
    internal static bool WillPathsConverge(
        Point start1, Point target1, int speed1,
        Point start2, Point target2, int speed2,
        int proximityThreshold = 500)
    {
        // Calculate direction vectors scaled to each entity's speed
        double dx1 = target1.X - start1.X;
        double dy1 = target1.Y - start1.Y;
        double dist1 = Math.Sqrt(dx1 * dx1 + dy1 * dy1);

        double dx2 = target2.X - start2.X;
        double dy2 = target2.Y - start2.Y;
        double dist2 = Math.Sqrt(dx2 * dx2 + dy2 * dy2);

        // Velocity vectors (units moved per step, i.e. over t in [0, 1])
        double vx1 = dist1 > 0 ? (dx1 / dist1) * speed1 : 0;
        double vy1 = dist1 > 0 ? (dy1 / dist1) * speed1 : 0;

        double vx2 = dist2 > 0 ? (dx2 / dist2) * speed2 : 0;
        double vy2 = dist2 > 0 ? (dy2 / dist2) * speed2 : 0;

        // Position at time t (0 <= t <= 1):
        //   P1(t) = start1 + t * v1
        //   P2(t) = start2 + t * v2
        //
        // Difference: D(t) = (start1 - start2) + t * (v1 - v2)
        double relX = start1.X - start2.X;
        double relY = start1.Y - start2.Y;
        double relVx = vx1 - vx2;
        double relVy = vy1 - vy2;

        // Squared distance: f(t) = (relX + t*relVx)^2 + (relY + t*relVy)^2
        //                        = a*t^2 + b*t + c
        double a = relVx * relVx + relVy * relVy;
        double b = 2.0 * (relX * relVx + relY * relVy);
        double c = relX * relX + relY * relY;

        double thresholdSq = (double)proximityThreshold * proximityThreshold;

        // Check start (t=0)
        if (c <= thresholdSq)
        {
            return true;
        }

        // Check end (t=1)
        double distSqAtEnd = a + b + c;
        if (distSqAtEnd <= thresholdSq)
        { 
            return true;
        }

        // If paths are not parallel/same velocity, check the minimum of the quadratic
        if (a > 0)
        {
            double tMin = -b / (2.0 * a);

            if (tMin > 0 && tMin < 1)
            {
                double minDistSq = a * tMin * tMin + b * tMin + c;
                if (minDistSq <= thresholdSq)
                {
                    return true;
                }
            }
        }

        return false;
    }

}

internal sealed class Drone
{
    internal int Id { get; private set; }

    internal Point Position { get; set; }
    internal int BatteryLevel { get; set; }

    internal HashSet<int> ScannedCreaturesIds { get; private set; } = new();

    internal Dictionary<int, CreatureDirection> CreatureDirections = new Dictionary<int, CreatureDirection>();

    internal Drone(int id, int xPos, int yPos, int batteryLevel)
    {
        Id = id;
        Position = new Point(xPos, yPos);
        BatteryLevel = batteryLevel;
    }

    internal void AddScannedCreatures(int id)
    {
        ScannedCreaturesIds.Add(id);
    }

    internal void AddCreatureDirection(int creatureId, CreatureDirection direction)
    {
        CreatureDirections[creatureId] = direction;
    }
}

internal class Game
{
    private const int _droneSpeed = 600;
    private const int _monsterDashSpeed = 540;
    private const int _captureSize = 500;

    internal int MyScore { get; set; }
    internal int EnemyScore { get; set; }

    private List<Creature> creatures = [];
    private List<Drone> myDrones = [];
    private List<Drone> enemyDrones = [];

    private Dictionary<int, bool> earlyGameTracker = new Dictionary<int, bool>();

    internal HashSet<int> MyStoredCreatureIds { get; private set; } = new();
    internal HashSet<int> EnemyStoredCreatureIds { get; private set; } = new();

    private DirectionCalculator _directionCalculator;
    private MonsterPositionCalculator _monsterPositionCalculator;

    internal int visibleCreatureCount;
    internal HashSet<int> VisibleMonsterIds { get; set; } = new();

    internal int round = 0;

    internal Dictionary<int, int> lastRoundTorchUsed = new();

    public Game()
    {
        earlyGameTracker.Add(0, true);
        earlyGameTracker.Add(1, true);
        earlyGameTracker.Add(2, true);
        earlyGameTracker.Add(3, true);
    }
    internal void InitialiseCreatures(List<Creature> allCreatures)
    {
        creatures = allCreatures;
        _directionCalculator = new DirectionCalculator(this);
        _monsterPositionCalculator = new MonsterPositionCalculator(this);
    }

    internal void AddStoredCreature(int creatureId, bool isMyDrone)
    {      
        if (isMyDrone)
        {
            MyStoredCreatureIds.Add(creatureId);
        }
        else
        {
            EnemyStoredCreatureIds.Add(creatureId);
        }
    }

    internal void SetMyDrones(List<Drone> drones)
    {
        myDrones = drones;
    }

    internal void SetEnemyDrones(List<Drone> drones)
    {
        enemyDrones = drones;
    }

    internal void UpdateCreaturePosition(int creatureId, int creatureX, int creatureY, int creatureVx, int creatureVy)
    {
        Creature creature = creatures.Find(c => c.Id == creatureId);
        if (creature != null)
        {
            creature.Position = new Point(creatureX, creatureY);
            creature.Velocity = new Point(creatureVx, creatureVy);
            creature.IsVisible = true;
            creature.LastSeenRound = round;

            if (creature.Type != -1)
            {
                visibleCreatureCount++;
            }
            else
            {
                VisibleMonsterIds.Add(creatureId);
            }
        }
    }

    internal void SetAllCreaturesAsNotVisible()
    {
        visibleCreatureCount = 0;

        foreach (var creature in creatures)
        {
            creature.IsVisible = false;
        }
    }

    internal List<string> CalculateActions()
    {
        // Logger.AllMonsters(creatures);

        var actions = new List<string>();

        // If a union of stored creatures and currently scanned creatures by both drones is equal to 12, we know all the creatures and can just head to the surface with all of them
        var allKnownCreatures = new HashSet<int>(MyStoredCreatureIds);
        allKnownCreatures.UnionWith(myDrones[0].ScannedCreaturesIds);
        allKnownCreatures.UnionWith(myDrones[1].ScannedCreaturesIds);

        foreach (var drone in myDrones)
        {
            Console.Error.WriteLine($"Drone {drone.Id}");
            var action = string.Empty;

            var lightLevel = CalculateLightLevel(drone);

            HashSet<int> monstersToAvoid = GetMonstersToAvoid(drone);

            //if (monstersToAvoid.Count > 0)
            //{
            //    earlyGame = false;

            //    Point avoidancePosition = CalculateAvoidanceVector(drone.Position, monstersToAvoid);
            //    action = $"MOVE {avoidancePosition.X} {avoidancePosition.Y} {lightLevel} RUNNING AWAY";

            //    actions.Add(action);
            //    continue;
            //}

            if (earlyGameTracker[drone.Id] == true)
            {
                // Drop to 8,000+ then rise to the top
                if (drone.Position.Y >= 8000)
                {
                    earlyGameTracker[drone.Id] = false;
                }

                // Move to the centre of it's side
                int xPos = 0;

                if (drone.Position.X < 5000)
                {
                    xPos = 2000;
                }
                else
                {
                    xPos = 8000;
                }

                // Calculate the exact targetPoint that's exactly 540 along the path from drone.Position to target
                Point targetPoint = DistanceCalculator.GetPointAlongPath(drone.Position, new Point(xPos, 9500), _droneSpeed);

                // Calculate exact next position of monsters to avoid and try to steer clear of them


                foreach (var monsterId in monstersToAvoid)
                {
                    Creature monster = creatures.Find(c => c.Id == monsterId);
                    Console.Error.WriteLine($"Monster {monster.Id} at position {monster.Position.X},{monster.Position.Y}");

                    Point monsterTarget = _monsterPositionCalculator.PredictTargetPosition(monster);

                    Console.Error.WriteLine($"Predicting monster will move to {monsterTarget.X},{monsterTarget.Y}");

                    // Should I avoid it
                    var willPathsConverge = DistanceCalculator.WillPathsConverge(drone.Position, targetPoint, _droneSpeed, monster.Position, monsterTarget, _monsterDashSpeed);
                    
                    if (willPathsConverge)
                    {
                        Console.Error.WriteLine($"Monster is within 500 of target point, adjusting to avoid");

                        if (drone.Position.X < monster.Position.X)
                        {
                            targetPoint.X = drone.Position.X - 600;
                            targetPoint.Y = drone.Position.Y;
                        }
                        else
                        {
                            targetPoint.X = drone.Position.X + 600;
                            targetPoint.Y = drone.Position.Y;
                        }
                    }
                    else
                    {
                        Console.Error.WriteLine($"Monster is not within 500");
                    }
                }


                actions.Add($"MOVE {targetPoint.X} {targetPoint.Y} {lightLevel} EARLY GAME DIVING");
                continue;
            }

            // TODO: Sometimes we'll want to head to surface for other reasons...
            if (allKnownCreatures.Count >= 12)
            {
                actions.Add($"MOVE {drone.Position.X} 500 {lightLevel} HEADING TO SURFACE");
                continue;
            }
            else
            {
                // Move in the direction of the most unscanned fish
                CreatureDirection direction = _directionCalculator.GetBestDirectionFromRadarBlips(drone);

                var targetPosition = new Point(0, 0);

                switch (direction)
                {
                    case CreatureDirection.TL:
                        targetPosition = new Point(drone.Position.X - 1000, drone.Position.Y - 1000);
                        break;
                    case CreatureDirection.TR:
                        targetPosition = new Point(drone.Position.X + 1000, drone.Position.Y - 1000);
                        break;
                    case CreatureDirection.BL:
                        targetPosition = new Point(drone.Position.X - 1000, drone.Position.Y + 1000);
                        break;
                    case CreatureDirection.BR:
                        targetPosition = new Point(drone.Position.X + 1000, drone.Position.Y + 1000);
                        break;
                }

                actions.Add($"MOVE {targetPosition.X} {targetPosition.Y} {lightLevel}  HEADING TO UNSCANNED FISH");
                continue;
            }
        }

        round++;

        return actions;
    }

    private HashSet<int> GetMonstersToAvoid(Drone drone)
    {
        HashSet<int> monstersToAvoid = new HashSet<int>();

        // First add visible monsters to the avoid list
        if (VisibleMonsterIds.Count > 0)
        {
            foreach (var monsterId in VisibleMonsterIds)
            {
                var monster = creatures.Find(c => c.Id == monsterId);

                var distanceToMonster = DistanceCalculator.GetDistance(drone.Position, monster.Position);

                if (distanceToMonster <= _droneSpeed + _monsterDashSpeed + _captureSize)
                {
                    monstersToAvoid.Add(monsterId);
                }
            }
        }

        // Now add close monsters seen last round to the avoid list
        //foreach (var creature in creatures)
        //{
        //    if (creature.Type != -1 || creature.IsVisible || creature.LastSeenRound == 0)
        //    {
        //        continue;
        //    }

        //    var distanceToMonster = DistanceCalculator.GetDistance(drone.Position, creature.Position);

        //    if ((round - creature.LastSeenRound == 1 && distanceToMonster <= _droneSpeed + (2 * _monsterDashSpeed) + _captureSize) ||
        //        (round - creature.LastSeenRound == 2 && distanceToMonster <= _droneSpeed + (3 * _monsterDashSpeed) + _captureSize))
        //    {
        //        monstersToAvoid.Add(creature.Id);
        //    }
        //}

        return monstersToAvoid;
    }

    private Point CalculateAvoidanceVector(Point dronePosition, HashSet<int> monstersToAvoid)
    {
        double totalForceX = 0;
        double totalForceY = 0;

        foreach (var monsterId in monstersToAvoid)
        {
            var monster = creatures.Find(c => c.Id == monsterId);
            var dx = dronePosition.X - monster.Position.X;
            var dy = dronePosition.Y - monster.Position.Y;
            var distance = Math.Sqrt(dx * dx + dy * dy);

            if (distance > 0)
            {
                // Normalize direction - each monster contributes equally
                totalForceX += dx / distance;
                totalForceY += dy / distance;
            }
        }

        // Normalize the combined vector and scale to movement speed
        var magnitude = Math.Sqrt(totalForceX * totalForceX + totalForceY * totalForceY);
        if (magnitude > 0)
        {
            totalForceX = (totalForceX / magnitude) * 600;
            totalForceY = (totalForceY / magnitude) * 600;
        }

        var targetX = dronePosition.X + (int)totalForceX;
        var targetY = dronePosition.Y + (int)totalForceY;

        // If near edge of map, redirect force vertically to avoid getting stuck on the wall
        if (targetX < 0 || targetX > 10000)
        {
            // Redirect horizontal force to vertical (move up)
            totalForceX = 0;

            if (targetY < dronePosition.Y)
            {
                targetY = dronePosition.Y - 600;
            }
            else
            {
                targetY = dronePosition.Y + 600;
            }
        }

        // If near bottom of map, redirect force horizontally to avoid getting stuck at the bottom
        if (targetY > 10000)
        {
            totalForceY = 0;

            if (targetX < dronePosition.X)
            {
                targetX = dronePosition.X - 600;
            }
            else
            {
                targetX = dronePosition.X + 600;
            }
        }

        // Clamp to map boundaries
        targetX = Math.Clamp(targetX, 0, 9999);
        targetY = Math.Clamp(targetY, 0, 9999);

        return new Point(targetX, targetY);
    }

    private int CalculateLightLevel(Drone drone)
    {
        var lightLevel = 0;

        if (lastRoundTorchUsed.ContainsKey(drone.Id))
        {
            var lastUsed = lastRoundTorchUsed[drone.Id];

            if (round - lastUsed >= 3)
            {
                lightLevel = 1;
                lastRoundTorchUsed[drone.Id] = round;
            }
        }
        else
        {
            lastRoundTorchUsed[drone.Id] = 0;
        }

        return lightLevel;
    }

    internal bool IsScannedByMe(int id)
    {
        foreach (var drone in myDrones)
        {
            if (drone.ScannedCreaturesIds.Contains(id))
            {
                return true;
            }
        }

        return false;
    }

    internal Drone GetNearestDrone(Creature monster)
    {
        Drone nearestDrone = null;
        double nearestDistance = double.MaxValue;
        foreach (var drone in myDrones)
        {
            var distance = DistanceCalculator.GetDistance(drone.Position, monster.Position);
            if (distance < nearestDistance)
            {
                nearestDistance = distance;
                nearestDrone = drone;
            }
        }

        foreach (var drone in enemyDrones)
        {
            var distance = DistanceCalculator.GetDistance(drone.Position, monster.Position);
            if (distance < nearestDistance)
            {
                nearestDistance = distance;
                nearestDrone = drone;
            }
        }

        return nearestDrone;
    }
}




internal static class Logger
{
    internal static void AllDrones(string? message, List<Drone> drones)
    {
        if (message != null)
        {
            Console.Error.WriteLine(message);
            Console.Error.WriteLine("==================================");
        }

        foreach (Drone drone in drones)
        {
            Drone(drone);
            Console.Error.WriteLine("------------------------");
        }
    }

    internal static void Drone(Drone drone)
    {
        Console.Error.WriteLine($"Drone {drone.Id}");
        Console.Error.WriteLine($"Position: {drone.Position.X},{drone.Position.Y}");
        Console.Error.WriteLine($"Battery:  {drone.BatteryLevel}");

        Console.Error.WriteLine($"Stored scans: {string.Join(" ", drone.ScannedCreaturesIds)}");

        Console.Error.WriteLine($"Creature directions: {string.Join(" ", drone.CreatureDirections.Select(kv => $"{kv.Key}:{kv.Value}"))}");
    }

    internal static void AllMonsters(List<Creature> creatures)
    {
        Console.Error.WriteLine("==================================");
        Console.Error.WriteLine("All Monsters");
        Console.Error.WriteLine("----------------------------------");

        foreach (Creature creature in creatures)
        {
            if (creature.Type != -1)
            {
                continue;
            }
            
            Creature(creature);
            Console.Error.WriteLine("------------------------");
        }
    }


    internal static void Creature(Creature creature)
    {
        Console.Error.WriteLine($"Creature {creature.Id}");
        Console.Error.WriteLine($"Visible: {creature.IsVisible}");
        Console.Error.WriteLine($"Last seen round: {creature.LastSeenRound}");
        Console.Error.WriteLine($"Type: {creature.Type}");
        Console.Error.WriteLine($"Color: {creature.Color}");
        Console.Error.WriteLine($"Position: {creature.Position.X},{creature.Position.Y}");
        Console.Error.WriteLine($"Velocity: {creature.Velocity.X},{creature.Velocity.Y}");
    }
}

internal sealed class MonsterPositionCalculator
{
    private readonly Game _game;
    public MonsterPositionCalculator(Game game)
    {
        _game = game;
    }

    internal Point PredictTargetPosition(Creature monster)
    {
        Console.Error.WriteLine($"Predicting position for monster {monster.Id}");
        // Get nearest drone
        // If nearest drone is using battery light is 2000, otherwise 800
        // If creature is within light radius, it will chase the nearest drone at 540 per turn
        var nearestDrone = _game.GetNearestDrone(monster);
        var lightRadius = nearestDrone.BatteryLevel == 1 ? 2000 : 800;

        var distanceToDrone = DistanceCalculator.GetDistance(monster.Position, nearestDrone.Position);
                
        if (distanceToDrone <= lightRadius)
        {
            // Monster will chase the nearest drone
            var direction = new Point(nearestDrone.Position.X - monster.Position.X, nearestDrone.Position.Y - monster.Position.Y);        
            var magnitude = Math.Sqrt(direction.X * direction.X + direction.Y * direction.Y);
            
            double normalisedX = direction.X / magnitude;
            double normalisedY = direction.Y / magnitude;

            Point targetPoint = new Point((int)(monster.Position.X + normalisedX * 540), (int)(monster.Position.Y + normalisedY * 540));

            return targetPoint;
        }
        else
        {
            // Monster will continue in the same direction
            // TOOD: Not always....
            return new Point(monster.Position.X + monster.Velocity.X, monster.Position.Y + monster.Velocity.Y);
        }
    }
}




class Player
{
    static void Main(string[] args)
    {
        var game = new Game();
        
        game.InitialiseCreatures(GetCreatures());

        // game loop
        while (true)
        {
            game.VisibleMonsterIds.Clear();

            int myScore = int.Parse(Console.ReadLine());
            game.MyScore = myScore;
            int foeScore = int.Parse(Console.ReadLine());
            game.EnemyScore = foeScore;

            AddStoredScans(game);

            List<Drone> myDrones = GetMyDrones();
            List<Drone> enemyDrones = GetEnemyDrones();

            AddStoredScans(myDrones, enemyDrones);

            UpdateCreatures(game);

            AddRadarBlips(game, myDrones, enemyDrones);

            game.SetMyDrones(myDrones);
            game.SetEnemyDrones(enemyDrones);

            List<string> actions = game.CalculateActions();

            foreach (string action in actions)
            {
                Console.WriteLine(action);
            }

            //Logger.AllDrones("My drones", myDrones);
            //Logger.AllDrones("Enemy drones", enemyDrones);
        }
    }    

    private static List<Creature> GetCreatures()
    {
        int creatureCount = int.Parse(Console.ReadLine());

        List<Creature> creatures = new List<Creature>();

        for (int i = 0; i < creatureCount; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            int creatureId = int.Parse(inputs[0]);
            int color = int.Parse(inputs[1]);
            int type = int.Parse(inputs[2]);

            creatures.Add(new Creature(creatureId, color, type));
        }

        return creatures;
    }

    private static void AddStoredScans(Game game)
    {
        int myScanCount = int.Parse(Console.ReadLine());
        for (int i = 0; i < myScanCount; i++)
        {
            int creatureId = int.Parse(Console.ReadLine());
            game.AddStoredCreature(creatureId, true);
        }
        int foeScanCount = int.Parse(Console.ReadLine());
        for (int i = 0; i < foeScanCount; i++)
        {
            int creatureId = int.Parse(Console.ReadLine());
            game.AddStoredCreature(creatureId, false);
        }
    }

    private static List<Drone> GetMyDrones()
    {
        int myDroneCount = int.Parse(Console.ReadLine());
        var myDrones = new List<Drone>();

        for (int i = 0; i < myDroneCount; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            int droneId = int.Parse(inputs[0]);
            int droneX = int.Parse(inputs[1]);
            int droneY = int.Parse(inputs[2]);
            int emergency = int.Parse(inputs[3]);
            int battery = int.Parse(inputs[4]);

            myDrones.Add(new Drone(droneId, droneX, droneY, battery));
        }

        return myDrones;
    }

    private static List<Drone> GetEnemyDrones()
    {
        int foeDroneCount = int.Parse(Console.ReadLine());
        var enemyDrones = new List<Drone>();

        for (int i = 0; i < foeDroneCount; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            int droneId = int.Parse(inputs[0]);
            int droneX = int.Parse(inputs[1]);
            int droneY = int.Parse(inputs[2]);
            int emergency = int.Parse(inputs[3]);
            int battery = int.Parse(inputs[4]);

            enemyDrones.Add(new Drone(droneId, droneX, droneY, battery));
        }

        return enemyDrones;
    }

    private static void UpdateCreatures(Game game)
    {
        game.SetAllCreaturesAsNotVisible();

        int visibleCreatureCount = int.Parse(Console.ReadLine());

        for (int i = 0; i < visibleCreatureCount; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            int creatureId = int.Parse(inputs[0]);
            int creatureX = int.Parse(inputs[1]);
            int creatureY = int.Parse(inputs[2]);
            int creatureVx = int.Parse(inputs[3]);
            int creatureVy = int.Parse(inputs[4]);

            game.UpdateCreaturePosition(creatureId, creatureX, creatureY, creatureVx, creatureVy);
        }
    }

    private static void AddStoredScans(List<Drone> myDrones, List<Drone> enemyDrones)
    {
        int droneScanCount = int.Parse(Console.ReadLine());
        for (int i = 0; i < droneScanCount; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            int droneId = int.Parse(inputs[0]);
            int creatureId = int.Parse(inputs[1]);

            Drone drone = myDrones.FirstOrDefault(d => d.Id == droneId);
            if (drone == null)
            {
                drone = enemyDrones.FirstOrDefault(d => d.Id == droneId);
            }

            if (drone != null)
            {
                drone.ScannedCreaturesIds.Add(creatureId);
            }
        }
    }
    
    private static void AddRadarBlips(Game game, List<Drone> myDrones, List<Drone> enemyDrones)
    {
        int radarBlipCount = int.Parse(Console.ReadLine());
        for (int i = 0; i < radarBlipCount; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            int droneId = int.Parse(inputs[0]);
            int creatureId = int.Parse(inputs[1]);
            string radar = inputs[2];

            Drone drone = myDrones.FirstOrDefault(d => d.Id == droneId);
            if (drone == null)
            {
                drone = enemyDrones.FirstOrDefault(d => d.Id == droneId);
            }

            if (drone != null)
            {
                drone.AddCreatureDirection(creatureId, (CreatureDirection)Enum.Parse(typeof(CreatureDirection), radar));
            }
        }
    }
}


