/**************************************************************
  This file was generated by FileConcatenator.
  It combined all classes in the project to work in Codingame.
***************************************************************/

using System.Drawing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Diagnostics;
using System.Text;
using System.Threading;
using System.Transactions;
using System.IO;
using System.Collections;
using System.Runtime.CompilerServices;

internal class Creature
{
    internal int Id { get; private set; }
    internal int Color { get; private set; }
    internal int Type { get; private set; }

    internal bool IsVisible { get; set; }
    internal Point Position { get; set; }
    internal Point Velocity { get; set; }

    internal int LastSeenRound { get; set; }

    internal Creature(int id, int color, int type)
    {
        Id = id;
        Color = color;
        Type = type;
    }
}


internal enum CreatureDirection
{
    TL,
    TR,
    BL,
    BR
}

internal class DirectionCalculator
{
    private Game game;

    public DirectionCalculator(Game game)
    {
        this.game = game;
    }

    internal CreatureDirection GetBestDirectionFromRadarBlips(Drone drone)
    {
        // First pass
        // Just go in the direction with the most creatures
        Dictionary<CreatureDirection, int> directionCounts = new Dictionary<CreatureDirection, int>();

        foreach (var direction in drone.CreatureDirections)
        {
            var incrementAmount = 0;

            // If a creature has been scanned/stored by me don't count it
            if (game.MyStoredCreatureIds.Contains(direction.Key) || drone.ScannedCreaturesIds.Contains(direction.Key))
            {
                incrementAmount = 0;
            }
            else if (!game.MyStoredCreatureIds.Contains(direction.Key) && !game.IsScannedByMe(direction.Key))
            {
                incrementAmount = 1;
            }           

            if (directionCounts.ContainsKey(direction.Value))
            {
                directionCounts[direction.Value] += incrementAmount;
            }
            else
            {
                directionCounts[direction.Value] = incrementAmount;
            }
        }

        // return the key with the highest value
        Console.Error.WriteLine($"Direction Counts: {string.Join(", ", directionCounts.Select(dc => $"{dc.Key}: {dc.Value}"))}");
        return directionCounts.MaxBy(dc => dc.Value).Key;
         
    }
}

internal static class DistanceCalculator
{
    internal static int GetDistance(Point position1, Point position2)
    {
        var dx = position1.X - position2.X;
        var dy = position1.Y - position2.Y;
        return (int)Math.Sqrt(dx * dx + dy * dy);
    }

    internal static Point GetPointAlongPath(Point position, Point target, int droneSpeed)
    {
        var dx = target.X - position.X;
        var dy = target.Y - position.Y;
        var distance = Math.Sqrt(dx * dx + dy * dy);
        if (distance == 0)
        {
            return position; // Already at the target
        }
        var ratio = droneSpeed / distance;
        var newX = (int)(position.X + dx * ratio);
        var newY = (int)(position.Y + dy * ratio);
        return new Point(newX, newY);
    }

    // Determines whether two objects, each moving linearly from start to target in one game turn,
    // will ever be within a given proximity (default 500 units) of each other during their movement.
    internal static bool WillPathsConverge(
        Point start1, Point target1,
        Point start2, Point target2,
        int proximityThreshold = 500)
    {
        // Velocity is simply (target - start) since each entity travels the full path in one turn (t in [0, 1])
        double vx1 = target1.X - start1.X;
        double vy1 = target1.Y - start1.Y;

        double vx2 = target2.X - start2.X;
        double vy2 = target2.Y - start2.Y;

        // Relative position and velocity
        double relX = start1.X - start2.X;
        double relY = start1.Y - start2.Y;
        double relVx = vx1 - vx2;
        double relVy = vy1 - vy2;

        // Squared distance: f(t) = (relX + t*relVx)^2 + (relY + t*relVy)^2
        //                        = a*t^2 + b*t + c
        double a = relVx * relVx + relVy * relVy;
        double b = 2.0 * (relX * relVx + relY * relVy);
        double c = relX * relX + relY * relY;

        double thresholdSq = (double)proximityThreshold * proximityThreshold;

        // Check start (t=0)
        if (c <= thresholdSq)
        {
            return true;
        }

        // Check end (t=1)
        double distSqAtEnd = a + b + c;
        if (distSqAtEnd <= thresholdSq)
        {
            return true;
        }

        // Check the minimum of the quadratic within [0, 1]
        if (a > 0)
        {
            double tMin = -b / (2.0 * a);

            if (tMin > 0 && tMin < 1)
            {
                double minDistSq = a * tMin * tMin + b * tMin + c;
                if (minDistSq <= thresholdSq)
                {
                    return true;
                }
            }
        }

        return false;
    }

}

internal sealed class Drone
{
    internal int Id { get; private set; }

    internal Point Position { get; set; }
    internal int BatteryLevel { get; set; }

    internal HashSet<int> ScannedCreaturesIds { get; private set; } = new();

    internal Dictionary<int, CreatureDirection> CreatureDirections = new Dictionary<int, CreatureDirection>();

    internal Drone(int id, int xPos, int yPos, int batteryLevel)
    {
        Id = id;
        Position = new Point(xPos, yPos);
        BatteryLevel = batteryLevel;
    }

    internal void AddCreatureDirection(int creatureId, CreatureDirection direction)
    {
        CreatureDirections[creatureId] = direction;
    }
}

internal class Game
{
    private const int _droneSpeed = 600;
    private const int _monsterDashSpeed = 540;
    private const int _captureSize = 500;

    internal int MyScore { get; set; }
    internal int EnemyScore { get; set; }

    private List<Creature> creatures = [];
    private List<Drone> myDrones = [];
    private List<Drone> enemyDrones = [];

    private Dictionary<int, bool> earlyGameTracker = new Dictionary<int, bool>();

    internal HashSet<int> MyStoredCreatureIds { get; private set; } = new();
    internal HashSet<int> EnemyStoredCreatureIds { get; private set; } = new();

    private DirectionCalculator _directionCalculator;
    private MonsterPositionCalculator _monsterPositionCalculator;

    internal int visibleCreatureCount;
    internal HashSet<int> VisibleMonsterIds { get; set; } = new();

    internal int round = 0;

    internal Dictionary<int, int> lastRoundTorchUsed = new();

    private static double angleStep = Math.PI / 6; // 30 degrees in radians
    private List<double> _leftDroneDownAlternativeAngles = new List<double> { angleStep, -angleStep, angleStep * 2, -(angleStep * 2), angleStep * 3, -(angleStep * 3), angleStep * 4, -(angleStep * 4), angleStep * 5, -(angleStep * 5), angleStep * 6, -(angleStep * 6) } ;
    private List<double> _rightDroneDownAlternativeAngles = new List<double> { -angleStep, angleStep, -(angleStep * 2), angleStep * 2, -(angleStep * 3), angleStep * 3, -(angleStep * 4), angleStep * 4, -(angleStep * 5), angleStep * 5, -(angleStep * 6), angleStep * 6 };

    public Game()
    {
        earlyGameTracker.Add(0, true);
        earlyGameTracker.Add(1, true);
        earlyGameTracker.Add(2, true);
        earlyGameTracker.Add(3, true);
    }
    internal void InitialiseCreatures(List<Creature> allCreatures)
    {
        creatures = allCreatures;
        _directionCalculator = new DirectionCalculator(this);
        _monsterPositionCalculator = new MonsterPositionCalculator(this);
    }

    internal void AddStoredCreature(int creatureId, bool isMyDrone)
    {      
        if (isMyDrone)
        {
            MyStoredCreatureIds.Add(creatureId);
        }
        else
        {
            EnemyStoredCreatureIds.Add(creatureId);
        }
    }

    internal void SetMyDrones(List<Drone> drones)
    {
        myDrones = drones;
    }

    internal void SetEnemyDrones(List<Drone> drones)
    {
        enemyDrones = drones;
    }

    internal void UpdateCreaturePosition(int creatureId, int creatureX, int creatureY, int creatureVx, int creatureVy)
    {
        Creature creature = creatures.Find(c => c.Id == creatureId);
        if (creature != null)
        {
            creature.Position = new Point(creatureX, creatureY);
            creature.Velocity = new Point(creatureVx, creatureVy);
            creature.IsVisible = true;
            creature.LastSeenRound = round;

            if (creature.Type != -1)
            {
                visibleCreatureCount++;
            }
            else
            {
                VisibleMonsterIds.Add(creatureId);
            }
        }
    }

    internal void SetAllCreaturesAsNotVisible()
    {
        visibleCreatureCount = 0;

        foreach (var creature in creatures)
        {
            creature.IsVisible = false;
        }
    }

    internal List<string> CalculateActions()
    {
        // Logger.AllMonsters(creatures);

        var actions = new List<string>();

        // If a union of stored creatures and currently scanned creatures by both drones is equal to 12, we know all the creatures and can just head to the surface with all of them
        var allKnownCreatures = new HashSet<int>(MyStoredCreatureIds);
        allKnownCreatures.UnionWith(myDrones[0].ScannedCreaturesIds);
        allKnownCreatures.UnionWith(myDrones[1].ScannedCreaturesIds);

        foreach (var drone in myDrones)
        {
            Console.Error.WriteLine($"Drone {drone.Id} pos: {drone.Position.X}, {drone.Position.Y}");
            var action = string.Empty;

            var lightLevel = CalculateLightLevel(drone);

            HashSet<int> monstersToAvoid = GetMonstersToAvoid(drone);

            // If we're below 8,000 or there are no more fish below, stop diving
            if (drone.Position.Y >= 8000 || !AreUnscannedFishStillBelow(drone))
            {
                Console.Error.WriteLine($"Drone {drone.Id} - No more unscanned fish below me or I've reached 8000+ depth, heading to surface and ending early game strategy");
                earlyGameTracker[drone.Id] = false;
            }

            if (earlyGameTracker[drone.Id] == true)
            {                

                // Move to the centre of it's side
                int xPos = 0;

                if (drone.Position.X < 5000)
                {
                    xPos = 2000;
                }
                else
                {
                    xPos = 8000;
                }

                // Calculate the exact targetPoint that's exactly _droneSpeed along the path from drone.Position to target
                Point targetPoint = DistanceCalculator.GetPointAlongPath(drone.Position, new Point(xPos, 9500), _droneSpeed);

                // Get the paths of all monsters we want to avoid and see if any of them will converge with our path to the target point (within 500)

                // If they will converge, adjust the path by 30 degrees either counter clocwise if they're the left drone, or clockwise if they're the right drone to try to avoid the monster. 
                // Then recheck the paths to see if we still converge, if so adjust further until we don't converge or we've adjusted 11 times (which would be a full circle,
                // so at that point we just accept the risk and move towards the target)
                int maxAdjustments = 11;
                double angleStep = Math.PI / 6; // 30 degrees in radians
                bool converged = false;
                int adjustmentCount = 0;
                Point originalTarget = DistanceCalculator.GetPointAlongPath(drone.Position, new Point(xPos, 9500), _droneSpeed);

                List<(Point start, Point end)> monsterPaths = GetAllMonsterPaths(monstersToAvoid);

                while (adjustmentCount < maxAdjustments)
                {
                    Console.Error.WriteLine($"Checking for target {targetPoint.X}, {targetPoint.Y}");
                    var willPathsConverge = false;
                    foreach (var monsterPath in monsterPaths)
                    {
                        if (DistanceCalculator.WillPathsConverge(drone.Position, targetPoint, monsterPath.start, monsterPath.end))
                        {
                            willPathsConverge = true;
                            break;
                        }
                    }

                    if (willPathsConverge)
                    {
                        Console.Error.WriteLine($"Drone {drone.Id} - Path converges with a monster, adjusting path. Adjustment count: {adjustmentCount}");
                        converged = true;
                        double dx = originalTarget.X - drone.Position.X;
                        double dy = originalTarget.Y - drone.Position.Y;
                        double angle = Math.Atan2(dy, dx);

                        if (drone.Position.X < 5000)
                        {
                            angle += _leftDroneDownAlternativeAngles[adjustmentCount];
                        }
                        else
                        {
                            angle += _rightDroneDownAlternativeAngles[adjustmentCount];
                        }

                        int newX = drone.Position.X + (int)(Math.Cos(angle) * _droneSpeed);
                        int newY = drone.Position.Y + (int)(Math.Sin(angle) * _droneSpeed);

                        newX = Math.Clamp(newX, 0, 9999);
                        newY = Math.Clamp(newY, 0, 9999);

                        targetPoint = new Point(newX, newY);
                        adjustmentCount++;
                    }
                    else
                    {
                        if (converged)
                        {
                            Console.Error.WriteLine($"Drone {drone.Id} - Found a path that doesn't converge with monsters after {adjustmentCount} adjustments.");
                        }
                        break;
                    }
                }

                actions.Add($"MOVE {targetPoint.X} {targetPoint.Y} {lightLevel} EARLY GAME DIVING");
                continue;
            }

            // TODO: Sometimes we'll want to head to surface for other reasons...
            if (allKnownCreatures.Count >= 12)
            {
                actions.Add($"MOVE {drone.Position.X} 500 {lightLevel} HEADING TO SURFACE");
                continue;
            }
            else
            {
                // Move in the direction of the most unscanned fish
                CreatureDirection direction = _directionCalculator.GetBestDirectionFromRadarBlips(drone);

                var targetPosition = new Point(0, 0);

                switch (direction)
                {
                    case CreatureDirection.TL:
                        targetPosition = new Point(drone.Position.X - 1000, drone.Position.Y - 1000);
                        break;
                    case CreatureDirection.TR:
                        targetPosition = new Point(drone.Position.X + 1000, drone.Position.Y - 1000);
                        break;
                    case CreatureDirection.BL:
                        targetPosition = new Point(drone.Position.X - 1000, drone.Position.Y + 1000);
                        break;
                    case CreatureDirection.BR:
                        targetPosition = new Point(drone.Position.X + 1000, drone.Position.Y + 1000);
                        break;
                }

                actions.Add($"MOVE {targetPosition.X} {targetPosition.Y} {lightLevel}  HEADING TO UNSCANNED FISH");
                continue;
            }
        }

        round++;

        return actions;
    }

    private bool AreUnscannedFishStillBelow(Drone drone)
    {
        foreach (var creature in drone.CreatureDirections)
        {
            if (creature.Value == CreatureDirection.BL || creature.Value == CreatureDirection.BR)
            {
                if (!IsScannedOrStoredByMe(creature.Key))
                {
                    Console.Error.WriteLine($"Creature {creature.Key} is below me and unscanned");
                    return true;
                }
            }
        }

        return false;
    }

    private bool IsScannedOrStoredByMe(int key)
    {
        if (MyStoredCreatureIds.Contains(key))
        {
            return true;
        }
        foreach (var drone in myDrones)
        {
            if (drone.ScannedCreaturesIds.Contains(key))
            {
                return true;
            }
        }
        return false;
    }

    private List<(Point start, Point end)> GetAllMonsterPaths(HashSet<int> monstersToAvoid)
    {
        var monsterPaths = new List<(Point start, Point end)>();
        foreach (var monsterId in monstersToAvoid)
        {
            Creature monster = creatures.Find(c => c.Id == monsterId);
            Point monsterTarget = _monsterPositionCalculator.PredictTargetPosition(monster);

            monsterPaths.Add((monster.Position, monsterTarget));
        }

        return monsterPaths;
    }

    private HashSet<int> GetMonstersToAvoid(Drone drone)
    {
        HashSet<int> monstersToAvoid = new HashSet<int>();

        // First add visible monsters to the avoid list
        if (VisibleMonsterIds.Count > 0)
        {
            foreach (var monsterId in VisibleMonsterIds)
            {
                var monster = creatures.Find(c => c.Id == monsterId);

                var distanceToMonster = DistanceCalculator.GetDistance(drone.Position, monster.Position);

                if (distanceToMonster <= _droneSpeed + _monsterDashSpeed + _captureSize)
                {
                    monstersToAvoid.Add(monsterId);
                }
            }
        }

        return monstersToAvoid;
    }

    private int CalculateLightLevel(Drone drone)
    {
        var lightLevel = 0;

        if (lastRoundTorchUsed.ContainsKey(drone.Id))
        {
            var lastUsed = lastRoundTorchUsed[drone.Id];

            if (round - lastUsed >= 3)
            {
                lightLevel = 1;
                lastRoundTorchUsed[drone.Id] = round;
            }
        }
        else
        {
            lastRoundTorchUsed[drone.Id] = 0;
        }

        return lightLevel;
    }

    internal bool IsScannedByMe(int id)
    {
        foreach (var drone in myDrones)
        {
            if (drone.ScannedCreaturesIds.Contains(id))
            {
                return true;
            }
        }

        return false;
    }

    internal Drone GetNearestDrone(Creature monster)
    {
        Drone nearestDrone = null;
        double nearestDistance = double.MaxValue;
        foreach (var drone in myDrones)
        {
            var distance = DistanceCalculator.GetDistance(drone.Position, monster.Position);
            if (distance < nearestDistance)
            {
                nearestDistance = distance;
                nearestDrone = drone;
            }
        }

        foreach (var drone in enemyDrones)
        {
            var distance = DistanceCalculator.GetDistance(drone.Position, monster.Position);
            if (distance < nearestDistance)
            {
                nearestDistance = distance;
                nearestDrone = drone;
            }
        }

        return nearestDrone;
    }
}





internal static class Logger
{
    internal static void AllDrones(string? message, List<Drone> drones)
    {
        if (message != null)
        {
            Console.Error.WriteLine(message);
            Console.Error.WriteLine("==================================");
        }

        foreach (Drone drone in drones)
        {
            Drone(drone);
            Console.Error.WriteLine("------------------------");
        }
    }

    internal static void Drone(Drone drone)
    {
        Console.Error.WriteLine($"Drone {drone.Id}");
        Console.Error.WriteLine($"Position: {drone.Position.X},{drone.Position.Y}");
        Console.Error.WriteLine($"Battery:  {drone.BatteryLevel}");

        Console.Error.WriteLine($"Stored scans: {string.Join(" ", drone.ScannedCreaturesIds)}");

        Console.Error.WriteLine($"Creature directions: {string.Join(" ", drone.CreatureDirections.Select(kv => $"{kv.Key}:{kv.Value}"))}");
    }

    internal static void AllMonsters(List<Creature> creatures)
    {
        Console.Error.WriteLine("==================================");
        Console.Error.WriteLine("All Monsters");
        Console.Error.WriteLine("----------------------------------");

        foreach (Creature creature in creatures)
        {
            if (creature.Type != -1)
            {
                continue;
            }
            
            Creature(creature);
            Console.Error.WriteLine("------------------------");
        }
    }


    internal static void Creature(Creature creature)
    {
        Console.Error.WriteLine($"Creature {creature.Id}");
        Console.Error.WriteLine($"Visible: {creature.IsVisible}");
        Console.Error.WriteLine($"Last seen round: {creature.LastSeenRound}");
        Console.Error.WriteLine($"Type: {creature.Type}");
        Console.Error.WriteLine($"Color: {creature.Color}");
        Console.Error.WriteLine($"Position: {creature.Position.X},{creature.Position.Y}");
        Console.Error.WriteLine($"Velocity: {creature.Velocity.X},{creature.Velocity.Y}");
    }
}

internal sealed class MonsterPositionCalculator
{
    private readonly Game _game;
    public MonsterPositionCalculator(Game game)
    {
        _game = game;
    }

    internal Point PredictTargetPosition(Creature monster)
    {
        // Get nearest drone
        // If nearest drone is using battery light is 2000, otherwise 800
        // If creature is within light radius, it will chase the nearest drone at 540 per turn
        var nearestDrone = _game.GetNearestDrone(monster);
        var lightRadius = nearestDrone.BatteryLevel == 1 ? 2000 : 800;

        var distanceToDrone = DistanceCalculator.GetDistance(monster.Position, nearestDrone.Position);
                
        if (distanceToDrone <= lightRadius)
        {
            // Monster will chase the nearest drone
            var direction = new Point(nearestDrone.Position.X - monster.Position.X, nearestDrone.Position.Y - monster.Position.Y);        
            var magnitude = Math.Sqrt(direction.X * direction.X + direction.Y * direction.Y);
            
            double normalisedX = direction.X / magnitude;
            double normalisedY = direction.Y / magnitude;

            Point targetPoint = new Point((int)(monster.Position.X + normalisedX * 540), (int)(monster.Position.Y + normalisedY * 540));

            return targetPoint;
        }
        else
        {
            // Monster will continue in the same direction
            // TOOD: Not always....
            return new Point(monster.Position.X + monster.Velocity.X, monster.Position.Y + monster.Velocity.Y);
        }
    }
}




class Player
{
    static void Main(string[] args)
    {
        var game = new Game();
        
        game.InitialiseCreatures(GetCreatures());

        // game loop
        while (true)
        {
            game.VisibleMonsterIds.Clear();

            int myScore = int.Parse(Console.ReadLine());
            game.MyScore = myScore;
            int foeScore = int.Parse(Console.ReadLine());
            game.EnemyScore = foeScore;

            AddStoredScans(game);

            List<Drone> myDrones = GetMyDrones();
            List<Drone> enemyDrones = GetEnemyDrones();

            AddStoredScans(myDrones, enemyDrones);

            UpdateCreatures(game);

            AddRadarBlips(game, myDrones, enemyDrones);

            game.SetMyDrones(myDrones);
            game.SetEnemyDrones(enemyDrones);

            List<string> actions = game.CalculateActions();

            foreach (string action in actions)
            {
                Console.WriteLine(action);
            }

            //Logger.AllDrones("My drones", myDrones);
            //Logger.AllDrones("Enemy drones", enemyDrones);
        }
    }    

    private static List<Creature> GetCreatures()
    {
        int creatureCount = int.Parse(Console.ReadLine());

        List<Creature> creatures = new List<Creature>();

        for (int i = 0; i < creatureCount; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            int creatureId = int.Parse(inputs[0]);
            int color = int.Parse(inputs[1]);
            int type = int.Parse(inputs[2]);

            creatures.Add(new Creature(creatureId, color, type));
        }

        return creatures;
    }

    private static void AddStoredScans(Game game)
    {
        int myScanCount = int.Parse(Console.ReadLine());
        for (int i = 0; i < myScanCount; i++)
        {
            int creatureId = int.Parse(Console.ReadLine());
            game.AddStoredCreature(creatureId, true);
        }
        int foeScanCount = int.Parse(Console.ReadLine());
        for (int i = 0; i < foeScanCount; i++)
        {
            int creatureId = int.Parse(Console.ReadLine());
            game.AddStoredCreature(creatureId, false);
        }
    }

    private static List<Drone> GetMyDrones()
    {
        int myDroneCount = int.Parse(Console.ReadLine());
        var myDrones = new List<Drone>();

        for (int i = 0; i < myDroneCount; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            int droneId = int.Parse(inputs[0]);
            int droneX = int.Parse(inputs[1]);
            int droneY = int.Parse(inputs[2]);
            int emergency = int.Parse(inputs[3]);
            int battery = int.Parse(inputs[4]);

            myDrones.Add(new Drone(droneId, droneX, droneY, battery));
        }

        return myDrones;
    }

    private static List<Drone> GetEnemyDrones()
    {
        int foeDroneCount = int.Parse(Console.ReadLine());
        var enemyDrones = new List<Drone>();

        for (int i = 0; i < foeDroneCount; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            int droneId = int.Parse(inputs[0]);
            int droneX = int.Parse(inputs[1]);
            int droneY = int.Parse(inputs[2]);
            int emergency = int.Parse(inputs[3]);
            int battery = int.Parse(inputs[4]);

            enemyDrones.Add(new Drone(droneId, droneX, droneY, battery));
        }

        return enemyDrones;
    }

    private static void UpdateCreatures(Game game)
    {
        game.SetAllCreaturesAsNotVisible();

        int visibleCreatureCount = int.Parse(Console.ReadLine());

        for (int i = 0; i < visibleCreatureCount; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            int creatureId = int.Parse(inputs[0]);
            int creatureX = int.Parse(inputs[1]);
            int creatureY = int.Parse(inputs[2]);
            int creatureVx = int.Parse(inputs[3]);
            int creatureVy = int.Parse(inputs[4]);

            game.UpdateCreaturePosition(creatureId, creatureX, creatureY, creatureVx, creatureVy);
        }
    }

    private static void AddStoredScans(List<Drone> myDrones, List<Drone> enemyDrones)
    {
        int droneScanCount = int.Parse(Console.ReadLine());
        for (int i = 0; i < droneScanCount; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            int droneId = int.Parse(inputs[0]);
            int creatureId = int.Parse(inputs[1]);

            Drone drone = myDrones.FirstOrDefault(d => d.Id == droneId);
            if (drone == null)
            {
                drone = enemyDrones.FirstOrDefault(d => d.Id == droneId);
            }

            if (drone != null)
            {
                drone.ScannedCreaturesIds.Add(creatureId);
            }
        }
    }
    
    private static void AddRadarBlips(Game game, List<Drone> myDrones, List<Drone> enemyDrones)
    {
        int radarBlipCount = int.Parse(Console.ReadLine());
        for (int i = 0; i < radarBlipCount; i++)
        {
            string[] inputs = Console.ReadLine().Split(' ');
            int droneId = int.Parse(inputs[0]);
            int creatureId = int.Parse(inputs[1]);
            string radar = inputs[2];

            Drone drone = myDrones.FirstOrDefault(d => d.Id == droneId);
            if (drone == null)
            {
                drone = enemyDrones.FirstOrDefault(d => d.Id == droneId);
            }

            if (drone != null)
            {
                drone.AddCreatureDirection(creatureId, (CreatureDirection)Enum.Parse(typeof(CreatureDirection), radar));
            }
        }
    }
}


