/**************************************************************
  This file was generated by FileConcatenator.
  It combined all classes in the project to work in Codingame.
***************************************************************/

using System.Drawing;
using System.Xml.Linq;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

internal static class CalculationUtil
{
    internal static int GetManhattanDistance(Point point1, Point point2)
    {
        return Math.Abs(point1.X - point2.X) + Math.Abs(point1.Y - point2.Y);

    }
}


internal static class DirectionHelper
{
    internal static string GetDirection(Point point1, Point point2)
    {
        if (point1.X < point2.X)
        {
            return "RIGHT";
        }
        else if (point1.X > point2.X)
        {
            return "LEFT";
        }
        else if (point1.Y < point2.Y)
        {
            return "DOWN";
        }
        else if (point1.Y > point2.Y)
        {
            return "UP";
        }
        else
        {
            throw new Exception($"Unable to determine direction from {point1} to {point2}");
        }
    }

    internal static Point GetNewPosition(Point point, string direction)
    {
        return direction switch
        {
            "UP" => new Point(point.X, point.Y - 1),
            "DOWN" => new Point(point.X, point.Y + 1),
            "LEFT" => new Point(point.X - 1, point.Y),
            "RIGHT" => new Point(point.X + 1, point.Y),
            _ => throw new Exception($"Unable to determine new position from {point} and direction {direction}")
        };
    }
}

internal class Game
{
    internal int Width { get; private set; }
    internal int Height { get; private set; }

    private Level _level;

    internal List<SnakeBot> MySnakeBots { get; set; }
    internal List<SnakeBot> OpponentSnakeBots { get; set; }

    private PathFinder _pathFinder;

    private List<Point> _movesThisTurn;

    public Game(int width, int height, bool[,] platforms)
    {
        Width = width;
        Height = height;

        _level = new Level(width, height, platforms);

        _pathFinder = new PathFinder(this);

        MySnakeBots = new List<SnakeBot>();
        OpponentSnakeBots = new List<SnakeBot>();
    }

    internal void MarkAllSnakesForRemoval()
    {
       foreach (var snakeBot in MySnakeBots)
        {
            snakeBot.Remove = true;
        }

        foreach (var snakeBot in OpponentSnakeBots)
        {
            snakeBot.Remove = true;
        }
    }

    internal void RemoveMarkedSnakes()
    {

        // Iterate through the snakes backwards to safely remove any where Remove == true
        for (int i = MySnakeBots.Count - 1; i >= 0; --i)
        {
            if (MySnakeBots[i].Remove)
            {
                MySnakeBots.RemoveAt(i);
            }
        }

        for (int i = OpponentSnakeBots.Count - 1; i >= 0; --i)
        {
            if (OpponentSnakeBots[i].Remove)
            {
                OpponentSnakeBots.RemoveAt(i);
            }
        }
    }

    internal void AddMySnake(SnakeBot snakeBot)
    {
        MySnakeBots.Add(snakeBot);
    }

    internal void AddOpponentSnake(SnakeBot snakeBot)
    {
        OpponentSnakeBots.Add(snakeBot);
    }

    internal SnakeBot GetSnake(int snakebotId)
    {
        return MySnakeBots.FirstOrDefault(s => s.Id == snakebotId) ?? OpponentSnakeBots.FirstOrDefault(s => s.Id == snakebotId);
    }

    internal void RemoveAllPowerSources()
    {
        _level.PowerSources.Clear();
    }

    internal void AddPowerSource(int x, int y)
    {
        _level.PowerSources.Add(new Point(x, y));
    }

    internal List<string> GetActions()
    {
        _movesThisTurn = new List<Point>();
        // Logger.EntireGame(_level.Platforms, MySnakeBots, OpponentSnakeBots, _level.PowerSources);

        List<string> actions = new List<string>();

        foreach (var snakeBot in MySnakeBots)
        {
            Console.Error.WriteLine($"Checking Snake {snakeBot.Id}");
            Console.Error.WriteLine($"_movesThisTurn: {string.Join(";", _movesThisTurn.Select(p => $"{p.X},{p.Y}"))}");
            int shortestPathCount = int.MaxValue;
            var shortestPathPoints = new List<Point>();

            // Use an iterative deepening approach to finding targets
            bool stopLooking = false;
            int maxDistance = 10;

            //while (stopLooking == false)
            //{
                Console.Error.WriteLine($"maxDistance: {maxDistance}");
                (List<Point> path, bool triedSomething) = GetShortestPath(snakeBot, Math.Min(shortestPathCount-1, maxDistance));

                if (path.Count > 0)
                {
                    Console.Error.WriteLine($"Found a path of length {path.Count} to a power source");
                    stopLooking = true;

                    shortestPathCount = path.Count;
                    shortestPathPoints = path.ToList();
                }

                if (stopLooking == false && triedSomething == true)
                {
                    // We tried a closer one and couldn't get to it. For now, don't try more
                    stopLooking = true;
                }                

            //    maxDistance += 5;
            //    if (maxDistance > 10)
            //    {
            //        stopLooking = true;
            //    }
            //}

            Console.Error.WriteLine(string.Join(";", shortestPathPoints.Select(p => $"{p.X},{p.Y}")));

            if (shortestPathPoints.Count == 0)
            {
                string direction = GetValidDirection(snakeBot);

                actions.Add($"{snakeBot.Id} {direction} ANY MOVE");
                snakeBot.AddMove(DirectionHelper.GetNewPosition(snakeBot.Body[0], direction));
                _movesThisTurn.Add(DirectionHelper.GetNewPosition(snakeBot.Body[0], direction));
            }
            else
            {
                Console.Error.WriteLine($"Patrh fount to {shortestPathPoints[shortestPathPoints.Count-1].X},{shortestPathPoints[shortestPathPoints.Count - 1].Y}, moving towards it");
                string direction = DirectionHelper.GetDirection(snakeBot.Body[0], shortestPathPoints[0]);

                actions.Add($"{snakeBot.Id} {direction} CHASING POWER");
                snakeBot.AddMove(shortestPathPoints[0]);
                _movesThisTurn.Add(shortestPathPoints[0]);
            }
        }

        return actions;
    }

    private string GetValidDirection(SnakeBot snakeBot)
    {
        var possibleDirections = new List<string>() { "UP", "DOWN", "LEFT", "RIGHT" };
        foreach (var direction in possibleDirections)
        {
            Point newHeadPosition = DirectionHelper.GetNewPosition(snakeBot.Body[0], direction);
            if (newHeadPosition.X >= 0
                && newHeadPosition.X < Width
                && newHeadPosition.Y >= 0
                && newHeadPosition.Y < Height
                && !IsPlatform(newHeadPosition)
                && !IsSnakePart(newHeadPosition, countTails: true, null)
                && _movesThisTurn.Contains(newHeadPosition) == false
                && !IsBlocking(newHeadPosition, snakeBot)
                && !ExcludeMove(newHeadPosition, snakeBot))
            {
                return direction;
            }
        }
        // No valid moves, just stay there and hope for the best
        return "LEFT";
    }

    private bool ExcludeMove(Point newHeadPosition, SnakeBot snakeBot)
    {
        if (snakeBot.IsStuck())
        {
            if (newHeadPosition == snakeBot.GetLastMove())
            {
                return true;
            }
        }

        return false;
    }

    private bool IsBlocking(Point newHeadPosition, SnakeBot snakeBot)
    {
        Console.Error.WriteLine($"Checking if move to {newHeadPosition.X},{newHeadPosition.Y} would block us in");
        // Flood fill algorithm to check if the new position would block the snake in
        var visited = new HashSet<Point>();
        var queue = new Queue<Point>();

        queue.Enqueue(newHeadPosition);
        visited.Add(newHeadPosition);

        while (queue.Count > 0)
        {
            Point checkPoint = queue.Dequeue();

            var adjacentPoints = new List<Point>()
            {
                new Point(checkPoint.X + 1, checkPoint.Y),
                new Point(checkPoint.X - 1, checkPoint.Y),
                new Point(checkPoint.X, checkPoint.Y + 1),
                new Point(checkPoint.X, checkPoint.Y - 1)
            };

            foreach (var adjacentPoint in adjacentPoints)
            {
                if (adjacentPoint.X >= 0
                    && adjacentPoint.X < Width
                    && adjacentPoint.Y >= 0
                    && adjacentPoint.Y < Height
                    && !IsPlatform(adjacentPoint)
                    && !IsSnakePart(adjacentPoint, countTails: true, null)
                    && !visited.Contains(adjacentPoint))
                {
                    queue.Enqueue(adjacentPoint);
                    visited.Add(adjacentPoint);
                }
            }
        }

        // If we visited less than 3 points, we are probably blocking ourselves in
        if (visited.Count < snakeBot.Body.Count)
        {
            return true;
        }

        return false;
    }

    private (List<Point>, bool) GetShortestPath(SnakeBot snakeBot, int maxDistance)
    {
        bool triedSomething = false;
        int shortestPathCount = int.MaxValue;
        var shortestPathPoints = new List<Point>();

        foreach (Point powerSource in _level.PowerSources)
        {
            // Don't bother trying if it's further away than the shortest one we've found
            if (CalculationUtil.GetManhattanDistance(snakeBot.Body[0], powerSource) >= maxDistance || CalculationUtil.GetManhattanDistance(snakeBot.Body[0], powerSource) >= shortestPathCount)
            {
                continue;
            }

            if (snakeBot.GetAttemptAtPowerSource(powerSource) > 20)
            {
                snakeBot.ClearAttemptsAtPowerSource(powerSource);
                continue;                
            }

            snakeBot.AddAttemptAtPowerSource(powerSource);

            List<Point> excludePoints = new List<Point>();
            if (snakeBot.IsStuck())
            {
                excludePoints.Add(snakeBot.GetLastMove());
            }

            List<Point> path = _pathFinder.GetShortestPath(snakeBot.Body.First(), powerSource, snakeBot, excludePoints.Concat(_movesThisTurn).ToList());
            triedSomething = true;

            if (path != null && path.Count > 0 && path.Count < shortestPathCount)
            {
                shortestPathCount = path.Count;
                shortestPathPoints = path.ToList();
            }
        }

        return (shortestPathPoints, triedSomething);
    }

    internal bool IsPlatform(Point pointToCheck)
    {
        if (IsOutOfBounds(pointToCheck))
        {
            return false;
        }

        if (_level.IsPlatform(pointToCheck))
        {
            return true;
        }

        return false;
    }

    private bool IsOutOfBounds(Point pointToCheck)
    {
        if (pointToCheck.X < 0 || pointToCheck.X >= Width || pointToCheck.Y < 0 || pointToCheck.Y >= Height)
        {
            return true;
        }
        return false;
    }

    internal bool IsSnakePart(Point pointToCheck, bool countTails, SnakeBot? excludeSnake)
    {
        foreach (var snakeBot in MySnakeBots)
        {
            if (excludeSnake != null && snakeBot == excludeSnake)
            {
                continue;
            }

            if(IsSnakePart(snakeBot, pointToCheck, countTails))
            {
                return true;
            }
        }

        foreach (var snakeBot in OpponentSnakeBots)
        {
            if (snakeBot.Body.Contains(pointToCheck))
            {
                if (IsSnakePart(snakeBot, pointToCheck, countTails))
                {
                    return true;
                }
            }
        }

        return false;
    }

    internal bool IsSnakePart(SnakeBot snakeBot, Point pointToCheck, bool countTails)
    {
        if (snakeBot.Body.Contains(pointToCheck))
        {
            if (!countTails)
            {
                if (snakeBot.Body[snakeBot.Body.Count - 1] == pointToCheck)
                {
                    return false;
                }
                else
                {
                    return true;
                }
            }
            else
            {
                return true;
            }
        }

        return false;
    }

    internal List<Point> GetPowerUps()
    {
        return _level.PowerSources;
    }
}


internal class Level
{
    private int width;
    private int height;

    internal bool[,] Platforms { get; private set; }

    internal List<Point> PowerSources { get; private set; } = new List<Point>();

    public Level(int width, int height, bool[,] platforms)
    {
        this.width = width;
        this.height = height;

        Platforms = platforms;
    }

    internal bool IsPlatform(Point pointToCheck)
    {
        return Platforms[pointToCheck.Y, pointToCheck.X];
    }
}


internal static class Logger    
{
    private static char _platformChar = '#';
    private static char _emptySpaceChar = '.';
    private static char _powerUpChar = '*';

    private static char _mySnakeHeadChar = '@';
    private static char _mySnakeBodyChar = 'o';

    private static char _opponentSnakeHeadChar = 'X';
    private static char _opponentSnakeBodyChar = 'x';

    internal static void Snakes(string debugMessage, List<SnakeBot> snakeBots)
    {
        Console.Error.WriteLine(debugMessage);
        Console.Error.WriteLine("-----------");
        foreach (var snakeBot in snakeBots)
        {
            Snake(snakeBot);
        }
    }

    internal static void Snake(SnakeBot snakeBot)
    {
        Console.Error.WriteLine($"SnakeBot {snakeBot.Id}: {string.Join(";", snakeBot.Body.Select(p => $"{p.X},{p.Y}"))}");
    }

    internal static void Platforms(bool[,] platforms)
    {
        Console.Error.WriteLine("Platforms:");
        for (int y = 0; y < platforms.GetLength(0); y++)
        {
            for (int x = 0; x < platforms.GetLength(1); x++)
            {
                if (platforms[y, x])
                {
                    Console.Error.Write(_platformChar);
                }
                else                
                {
                    Console.Error.Write(" ");
                }
            }
            Console.Error.WriteLine();
        }
    }

    internal static void EntireGame(bool[,] platforms, List<SnakeBot> mySnakeBots, List<SnakeBot> opponentSnakeBots, List<System.Drawing.Point> powerSources)
    {
        Console.Error.WriteLine("Platforms:");
        for (int y = 0; y < platforms.GetLength(0); y++)
        {
            for (int x = 0; x < platforms.GetLength(1); x++)
            {
                if (platforms[y, x])
                {
                    Console.Error.Write(_platformChar);
                }
                else
                {
                    bool charPlaced = false;
                    // check if a snake is in this position
                    foreach (var bot in mySnakeBots)
                    {
                        if (bot.Body.Any(p => p.X == x && p.Y == y))
                        {
                            if (bot.Body[0].X == x && bot.Body[0].Y == y)
                            {                                
                                Console.Error.Write(_mySnakeHeadChar);
                                charPlaced = true;
                                break;
                            }
                            else
                            {
                                Console.Error.Write(_mySnakeBodyChar);
                                charPlaced = true;
                                break;
                            }
                        }
                    }

                    if (charPlaced)
                    {
                        continue;
                    }

                    foreach (var bot in opponentSnakeBots)
                    {
                        if (bot.Body.Any(p => p.X == x && p.Y == y))
                        {
                            if (bot.Body[0].X == x && bot.Body[0].Y == y)
                            {
                                Console.Error.Write(_opponentSnakeHeadChar);
                                charPlaced = true;
                                break;
                            }
                            else
                            {
                                Console.Error.Write(_opponentSnakeBodyChar);
                                charPlaced = true;
                                break;
                            }
                        }
                    }

                    if (charPlaced)
                    {
                        continue;
                    }

                    foreach(var powerUp in powerSources)
                    {
                        if (powerUp.X == x && powerUp.Y == y)
                        {
                            Console.Error.Write(_powerUpChar);
                            charPlaced = true;
                            break;
                        }
                    }

                    if (charPlaced)
                    {
                        continue;
                    }



                    Console.Error.Write(_emptySpaceChar);
                }
            }
            Console.Error.WriteLine();
        }
    }
}

internal sealed class Node
{
    public Point Position { get; set; }

    public Point Parent { get; set; }

    public int G { get; set; }
    public int H { get; set; }
    public int F { get; set; }

    public bool Closed { get; set; }

    public List<Point> SnakeBodyAtNode { get; set; } = new List<Point>();

    public Node(Point position)
    {
        Position = position;
    }
}


internal sealed class PathFinder
{
    private Game _game;

    private int _debugCount = 0;

    public PathFinder(Game game)
    {
        _game = game;
    }

    internal List<Point> GetShortestPath(Point startPoint, Point targetPoint, SnakeBot snake, List<Point> excludePoints)
    {
        _debugCount = 0;
        SnakeBot currentSnake = new SnakeBot(snake.Id)
        {
            Body = snake.Body.Select(p => new Point(p.X, p.Y)).ToList()
        };

        List<Node> nodes = new List<Node>();

        Node currentNode = new Node(startPoint);
        currentNode.SnakeBodyAtNode = snake.Body.Select(p => new Point(p.X, p.Y)).ToList();
        nodes.Add(currentNode);

        bool targetFound = false;

        while (!targetFound)
        {
            if (nodes.Count(n => n.Closed == false) == 0)
            {
                return new List<Point>();
            }

            if (nodes.Count > 20)
            {
                Console.Error.WriteLine("Too many nodes, breaking out of loop");
                return new List<Point>();
            }

            Point[] pointsToCheck = new Point[4];

            // Prioritise heading towards the target as the first move
            if (Math.Abs(currentNode.Position.X - targetPoint.X) >= Math.Abs(currentNode.Position.Y - targetPoint.Y))
            {
                pointsToCheck[0] = new Point(Math.Min(_game.Width, currentNode.Position.X + 1), currentNode.Position.Y);
                pointsToCheck[1] = new Point(Math.Max(-1, currentNode.Position.X - 1), currentNode.Position.Y);
                pointsToCheck[2] = new Point(currentNode.Position.X, Math.Min(_game.Height, currentNode.Position.Y + 1));
                pointsToCheck[3] = new Point(currentNode.Position.X, Math.Max(-1, currentNode.Position.Y - 1));
            }
            else
            {
                pointsToCheck[0] = new Point(currentNode.Position.X, Math.Min(_game.Height, currentNode.Position.Y + 1));
                pointsToCheck[1] = new Point(currentNode.Position.X, Math.Max(-1, currentNode.Position.Y - 1));
                pointsToCheck[2] = new Point(Math.Min(_game.Width, currentNode.Position.X + 1), currentNode.Position.Y);
                pointsToCheck[3] = new Point(Math.Max(-1, currentNode.Position.X - 1), currentNode.Position.Y);
            }

            foreach (Point pointToCheck in pointsToCheck)
            {
                // If there is only one node, we are at the start and we want to ignore the excludePoints
                if (nodes.Count == 1 && excludePoints.Contains(pointToCheck))
                {
                    continue;
                }

                // Simulate snake movement to this position
                List<Point> snakeBodyAfterMove = SimulateSnakeMovement(
                    currentNode.SnakeBodyAtNode,
                    currentNode.Position,
                    pointToCheck);

                // Apply gravity to the simulated body
                snakeBodyAfterMove = ApplyGravity(snakeBodyAfterMove, currentSnake.Id);

                // IMPORTANT: After gravity, the head position may have changed!
                Point actualHeadPosition = snakeBodyAfterMove[0];

                // Check if a node at this actual position already exists
                Node? existingNode = nodes.SingleOrDefault(n => n.Position == actualHeadPosition);

                if (existingNode == null)
                {
                    // Check if the intended move is valid (before gravity)
                    if (pointToCheck == startPoint
                        || pointToCheck == targetPoint
                        || !IsPlatform(pointToCheck, snake, currentSnake))
                    {
                        // Create node at the ACTUAL position after gravity
                        Node node = new Node(actualHeadPosition);
                        node.Parent = currentNode.Position;
                        node.G = currentNode.G + 1;
                        node.H = CalculationUtil.GetManhattanDistance(actualHeadPosition, targetPoint);
                        node.F = node.G + node.H;
                        node.SnakeBodyAtNode = snakeBodyAfterMove;

                        nodes.Add(node);
                    }
                }
                else
                {
                    if (!existingNode.Closed)
                    {
                        int g = currentNode.G + 1;

                        if (g < existingNode.G)
                        {
                            existingNode.G = g;
                            existingNode.F = existingNode.G + existingNode.H;
                            existingNode.Parent = currentNode.Position;
                            existingNode.SnakeBodyAtNode = snakeBodyAfterMove;
                        }
                    }
                }
            }

            currentNode.Closed = true;

            if (currentNode.Position == targetPoint)
            {
                targetFound = true;
            }
            else
            {
                nodes = nodes.OrderBy(n => n.Closed == true).ThenBy(n => n.F).ToList();

                var openNode = nodes.FirstOrDefault(n => !n.Closed);
                if (openNode == null)
                {
                    return new List<Point>();
                }

                currentNode = openNode;
            }

            _debugCount++;
        }

        Console.Error.WriteLine($"Debug count: {_debugCount}");

        // Build the path - but we need to return the MOVES, not the final positions
        List<Point> shortestPath = new List<Point>();
        Node pathNode = currentNode;

        while (pathNode.Parent != default(Point))
        {
            Node parentNode = nodes.Single(n => n.Position == pathNode.Parent);

            // The move is the direction from parent's ACTUAL position to the intermediate position
            // before gravity was applied in pathNode
            shortestPath.Insert(0, pathNode.Position);
            pathNode = parentNode;
        }

        Console.Error.WriteLine("Created shortestPath");

        return shortestPath;
    }

    private List<Point> ApplyGravity(List<Point> snakeBody, int id)
    {
        bool canMoveDown = true;
        while (canMoveDown)
        {
            // Check if we can move down
            if (snakeBody.Any(p => p.Y + 1 >= _game.Height
                                || _game.IsPlatform(new Point(p.X, p.Y + 1))
                                || _game.MySnakeBots.Any(s => s.Body.Any(bp => bp.X == p.X && bp.Y == p.Y + 1 && s.Id != id))
                                || _game.OpponentSnakeBots.Any(s => s.Body.Any(bp => bp.X == p.X && bp.Y == p.Y + 1 && s.Id != id))
                                || _game.GetPowerUps().Any(pu => pu.X == p.X && pu.Y == p.Y + 1)))
            {
                canMoveDown = false;
            }
            else
            {
                // Move the snake down by one
                for (int i = 0; i < snakeBody.Count; ++i)
                {
                    snakeBody[i] = new Point(snakeBody[i].X, snakeBody[i].Y + 1);
                }
            }
        }

        return snakeBody;
    }

    private List<Point> SimulateSnakeMovement(List<Point> currentBody, Point currentHead, Point newHead)
    {
        List<Point> newBody = currentBody.Select(p => new Point(p.X, p.Y)).ToList();
        newBody.Insert(0, newHead);

        List <Point> powerSources = _game.GetPowerUps();

        if(powerSources.Contains(newHead))
        {
            // Don't remove the tail if we are eating a power source
            return newBody;
        }

        newBody.RemoveAt(newBody.Count - 1);

        return newBody;
    }

    private bool IsPlatform(Point pointToCheck, SnakeBot excludeSnake, SnakeBot currentSnake)
    {
        // Check that it's not a platform

        // Check that it's not a snakes head or body

        if (_game.IsPlatform(pointToCheck))
        {
            return true;
        }


        // Check all snakes except the current one
        if (_game.IsSnakePart(pointToCheck, countTails: true, excludeSnake: excludeSnake))
        {
            return true; 
        }

        // Check the current snake
        if (_game.IsSnakePart(currentSnake, pointToCheck, countTails: false))
        {
            return true;
        }

        return false;
    }    
}


internal class Player
{
    static void Main(string[] args)
    {        
        string[] inputs;
        int myId = int.Parse(Console.ReadLine());
        int width = int.Parse(Console.ReadLine());
        int height = int.Parse(Console.ReadLine());


        bool[,] platforms = new bool[height, width];
        for (int y = 0; y < height; y++)
        {            
            string row = Console.ReadLine();

            char[] splitRow = row.ToCharArray();
            for (int x = 0; x < width; x++)
            {
                platforms[y, x] = splitRow[x] == '#';
            }
        }

        Game game = new Game(width, height, platforms);

        int snakebotsPerPlayer = int.Parse(Console.ReadLine());
        for (int i = 0; i < snakebotsPerPlayer; i++)
        {
            int mySnakebotId = int.Parse(Console.ReadLine());
            game.AddMySnake(new SnakeBot(mySnakebotId));

        }
        for (int i = 0; i < snakebotsPerPlayer; i++)
        {
            int oppSnakebotId = int.Parse(Console.ReadLine());
            game.AddOpponentSnake(new SnakeBot(oppSnakebotId));
        }

        Logger.Platforms(platforms);

        // game loop
        while (true)
        {
            game.MarkAllSnakesForRemoval();

            game.RemoveAllPowerSources();
            int powerSourceCount = int.Parse(Console.ReadLine());
            for (int i = 0; i < powerSourceCount; i++)
            {
                inputs = Console.ReadLine().Split(' ');
                int x = int.Parse(inputs[0]);
                int y = int.Parse(inputs[1]);

                game.AddPowerSource(x, y);
            }

            int snakebotCount = int.Parse(Console.ReadLine());
            for (int i = 0; i < snakebotCount; i++)
            {
                inputs = Console.ReadLine().Split(' ');
                int snakebotId = int.Parse(inputs[0]);
                string body = inputs[1];

                SnakeBot snakeBot = game.GetSnake(snakebotId);

                if (snakeBot != null)
                {
                    snakeBot.Remove = false;
                    snakeBot.Body.Clear();
                    string[] segments = body.Split(':');
                    foreach (string segment in segments)
                    {
                        string[] coordinates = segment.Split(',');
                        int x = int.Parse(coordinates[0]);
                        int y = int.Parse(coordinates[1]);
                        snakeBot.Body.Add(new Point(x, y));
                    }
                }
            }

            game.RemoveMarkedSnakes();

            // Write an action using Console.WriteLine()
            // To debug: Console.Error.WriteLine("Debug messages...");

            // Logger.Snakes("My snake Bots", mySnakeBots);
            // Logger.Snakes("My snake Bots", mySnakeBots);

            List<string> actions = game.GetActions();   
            
            Console.WriteLine(string.Join(";", actions));
        }
    }
}


internal class SnakeBot
{
    internal int Id { get; }
    internal List<Point> Body { get; set; }
    
    internal bool Remove { get; set; }

    private List<Point> previousMoves = new List<Point>();

    private Dictionary<Point, int> _attemptsAtPowerSources = new Dictionary<Point, int>();

    internal SnakeBot(int id)
    {
        Id = id;

        Body = new List<Point>();
    }

    internal void AddMove(Point move)
    {
        previousMoves.Add(move);
    }

    internal bool IsStuck()
    {
        if (previousMoves.Count < 4)
        {
            return false;
        }

        int repetitions = 0;
        Point LastMove = previousMoves.Last();

        for (int i = previousMoves.Count - 2; i >= 0; --i)
        {
            if (previousMoves[i] == previousMoves.Last())
            {
                repetitions++;
            }
            else
            {
                break;
            }
        }

        if (repetitions > 3)
        {
            return true;
        }

        return false;
    }

    internal Point GetLastMove()
    {
        if (previousMoves.Count == 0)
        {
            return new Point(-1, -1);
        }
        return previousMoves.Last();
    }

    internal void AddAttemptAtPowerSource(Point powerSource)
    {
        if (_attemptsAtPowerSources.ContainsKey(powerSource))
        {
            _attemptsAtPowerSources[powerSource]++;
        }
        else
        {
            _attemptsAtPowerSources[powerSource] = 1;
        }
    }

    internal int GetAttemptAtPowerSource(Point powerSource)
    {
        if (_attemptsAtPowerSources.ContainsKey(powerSource))
        {
            return _attemptsAtPowerSources[powerSource];
        }
        else
        {
            return 0;
        }
    }

    internal void ClearAttemptsAtPowerSource(Point powerSource)
    {
        if (_attemptsAtPowerSources.ContainsKey(powerSource))
        {
            _attemptsAtPowerSources.Remove(powerSource);
        }
    }
}



