/**************************************************************
  This file was generated by FileConcatenator.
  It combined all classes in the project to work in Codingame.
***************************************************************/

using System.Drawing;
using System.Xml.Linq;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

internal static class CalculationUtil
{
    internal static int GetManhattanDistance(Point point1, Point point2)
    {
        return Math.Abs(point1.X - point2.X) + Math.Abs(point1.Y - point2.Y);

    }
}


internal static class DirectionHelper
{
    internal static string GetDirection(Point point1, Point point2)
    {
        if (point1.X < point2.X)
        {
            return "RIGHT";
        }
        else if (point1.X > point2.X)
        {
            return "LEFT";
        }
        else if (point1.Y < point2.Y)
        {
            return "DOWN";
        }
        else if (point1.Y > point2.Y)
        {
            return "UP";
        }
        else
        {
            throw new Exception($"Unable to determine direction from {point1} to {point2}");
        }
    }

    internal static Point GetNewPosition(Point point, string direction)
    {
        return direction switch
        {
            "UP" => new Point(point.X, point.Y - 1),
            "DOWN" => new Point(point.X, point.Y + 1),
            "LEFT" => new Point(point.X - 1, point.Y),
            "RIGHT" => new Point(point.X + 1, point.Y),
            _ => throw new Exception($"Unable to determine new position from {point} and direction {direction}")
        };
    }
}

internal class Game
{
    internal int Width { get; private set; }
    internal int Height { get; private set; }

    private Level _level;

    internal List<SnakeBot> MySnakeBots { get; set; }
    internal List<SnakeBot> OpponentSnakeBots { get; set; }

    private PathFinder _pathFinder;

    public Game(int width, int height, bool[,] platforms)
    {
        Width = width;
        Height = height;

        _level = new Level(width, height, platforms);

        _pathFinder = new PathFinder(this);

        MySnakeBots = new List<SnakeBot>();
        OpponentSnakeBots = new List<SnakeBot>();
    }

    internal void MarkAllSnakesForRemoval()
    {
       foreach (var snakeBot in MySnakeBots)
        {
            snakeBot.Remove = true;
        }

        foreach (var snakeBot in OpponentSnakeBots)
        {
            snakeBot.Remove = true;
        }
    }

    internal void RemoveMarkedSnakes()
    {

        // Iterate through the snakes backwards to safely remove any where Remove == true
        for (int i = MySnakeBots.Count - 1; i >= 0; --i)
        {
            if (MySnakeBots[i].Remove)
            {
                MySnakeBots.RemoveAt(i);
            }
        }

        for (int i = OpponentSnakeBots.Count - 1; i >= 0; --i)
        {
            if (OpponentSnakeBots[i].Remove)
            {
                OpponentSnakeBots.RemoveAt(i);
            }
        }
    }

    internal void AddMySnake(SnakeBot snakeBot)
    {
        MySnakeBots.Add(snakeBot);
    }

    internal void AddOpponentSnake(SnakeBot snakeBot)
    {
        OpponentSnakeBots.Add(snakeBot);
    }

    internal SnakeBot GetSnake(int snakebotId)
    {
        return MySnakeBots.FirstOrDefault(s => s.Id == snakebotId) ?? OpponentSnakeBots.FirstOrDefault(s => s.Id == snakebotId);
    }

    internal void RemoveAllPowerSources()
    {
        _level.PowerSources.Clear();
    }

    internal void AddPowerSource(int x, int y)
    {
        _level.PowerSources.Add(new Point(x, y));
    }

    internal List<string> GetActions()
    {
        // Logger.EntireGame(_level.Platforms, MySnakeBots, OpponentSnakeBots, _level.PowerSources);

        List<string> actions = new List<string>();

        foreach (var snakeBot in MySnakeBots)
        {
            Console.Error.WriteLine($"Checking Snake {snakeBot.Id}");
            int shortestPathCount = int.MaxValue;
            var shortestPathPoints = new List<Point>();

            // Use an iterative deepening approach to finding targets
            bool stopLooking = false;
            int maxDistance = 5;

            while (stopLooking == false)
            {
                Console.Error.WriteLine($"Trying to find target within distance {Math.Min(shortestPathCount - 1, maxDistance)}");

                (List<Point> path, bool triedSomething) = GetShortestPath(snakeBot, Math.Min(shortestPathCount-1, maxDistance));

                if (path.Count > 0)
                {
                    stopLooking = true;

                    shortestPathCount = path.Count;
                    shortestPathPoints = path.ToList();

                    Console.Error.WriteLine($"Path found at {string.Join(",", shortestPathPoints)}");
                }

                if (stopLooking == false && triedSomething == true)
                {
                    Console.Error.WriteLine($"No targets found but we tried. Don't bother trying again");
                    // We tried a closer one and couldn't get to it. For now, don't try more
                    stopLooking = true;
                }                

                maxDistance += 5;
            }

            Console.Error.WriteLine(string.Join(";", shortestPathPoints.Select(p => $"{p.X},{p.Y}")));

            if (shortestPathPoints.Count == 0)
            {
                // TODO: Don't just stay there. See if there are any valid moves
                var direction = GetValidDirection(snakeBot);

                actions.Add($"{snakeBot.Id} {direction}");
            }
            else
            {
                string direction = DirectionHelper.GetDirection(snakeBot.Body[0], shortestPathPoints[0]);

                actions.Add($"{snakeBot.Id} {direction}");
            }
        }

        return actions;
    }

    private object GetValidDirection(SnakeBot snakeBot)
    {
        var possibleDirections = new List<string>() { "UP", "DOWN", "LEFT", "RIGHT" };
        foreach (var direction in possibleDirections)
        {
            Point newHeadPosition = DirectionHelper.GetNewPosition(snakeBot.Body[0], direction);
            if (newHeadPosition.X >= 0
                && newHeadPosition.X < Width
                && newHeadPosition.Y >= 0
                && newHeadPosition.Y < Height
                && !IsPlatform(newHeadPosition)
                && !IsSnakePart(newHeadPosition, countTails: false))
            {
                return direction;
            }
        }
        // No valid moves, just stay there and hope for the best
        return "DOWN";
    }

    private (List<Point>, bool) GetShortestPath(SnakeBot snakeBot, int maxDistance)
    {
        bool triedSomething = false;
        int shortestPathCount = int.MaxValue;
        var shortestPathPoints = new List<Point>();

        foreach (Point powerSource in _level.PowerSources)
        {
            // Don't bother trying if it's further away than the shortest one we've found
            if (CalculationUtil.GetManhattanDistance(snakeBot.Body[0], powerSource) >= maxDistance)
            {
                continue;
            }

            List<Point> path = _pathFinder.GetShortestPath(snakeBot.Body.First(), powerSource, snakeBot);
            triedSomething = true;

            if (path != null && path.Count > 0 && path.Count < shortestPathCount)
            {
                shortestPathCount = path.Count;
                shortestPathPoints = path.ToList();
            }
        }

        return (shortestPathPoints, triedSomething);
    }

    internal bool IsPlatform(Point pointToCheck)
    {
        if (_level.IsPlatform(pointToCheck))
        {
            return true;
        }

        return false;
    }

    internal bool IsSnakePart(Point pointToCheck, bool countTails)
    {
        foreach (var snakeBot in MySnakeBots)
        {
            if (snakeBot.Body.Contains(pointToCheck))
            {
                if (!countTails)
                {
                    if(snakeBot.Body[snakeBot.Body.Count - 1] == pointToCheck)
                    {
                        return false;
                    }
                    else
                    {
                        return true;
                    }
                }
                else
                {
                    return true;
                }
            }
        }

        foreach (var snakeBot in OpponentSnakeBots)
        {
            if (snakeBot.Body.Contains(pointToCheck))
            {
                if (!countTails)
                {
                    if (snakeBot.Body[snakeBot.Body.Count - 1] == pointToCheck)
                    {
                        return false;
                    }
                    else
                    {
                        return true;
                    }
                }
                else
                {
                    return true;
                }
            }
        }

        return false;
    }
}


internal class Level
{
    private int width;
    private int height;

    internal bool[,] Platforms { get; private set; }

    internal List<Point> PowerSources { get; private set; } = new List<Point>();

    public Level(int width, int height, bool[,] platforms)
    {
        this.width = width;
        this.height = height;

        Platforms = platforms;
    }

    internal bool IsPlatform(Point pointToCheck)
    {
        return Platforms[pointToCheck.Y, pointToCheck.X];
    }
}


internal static class Logger    
{
    private static char _platformChar = '#';
    private static char _emptySpaceChar = '.';
    private static char _powerUpChar = '*';

    private static char _mySnakeHeadChar = '@';
    private static char _mySnakeBodyChar = 'o';

    private static char _opponentSnakeHeadChar = 'X';
    private static char _opponentSnakeBodyChar = 'x';

    internal static void Snakes(string debugMessage, List<SnakeBot> snakeBots)
    {
        Console.Error.WriteLine(debugMessage);
        Console.Error.WriteLine("-----------");
        foreach (var snakeBot in snakeBots)
        {
            Snake(snakeBot);
        }
    }

    internal static void Snake(SnakeBot snakeBot)
    {
        Console.Error.WriteLine($"SnakeBot {snakeBot.Id}: {string.Join(";", snakeBot.Body.Select(p => $"{p.X},{p.Y}"))}");
    }

    internal static void Platforms(bool[,] platforms)
    {
        Console.Error.WriteLine("Platforms:");
        for (int y = 0; y < platforms.GetLength(0); y++)
        {
            for (int x = 0; x < platforms.GetLength(1); x++)
            {
                if (platforms[y, x])
                {
                    Console.Error.Write(_platformChar);
                }
                else                
                {
                    Console.Error.Write(" ");
                }
            }
            Console.Error.WriteLine();
        }
    }

    internal static void EntireGame(bool[,] platforms, List<SnakeBot> mySnakeBots, List<SnakeBot> opponentSnakeBots, List<System.Drawing.Point> powerSources)
    {
        Console.Error.WriteLine("Platforms:");
        for (int y = 0; y < platforms.GetLength(0); y++)
        {
            for (int x = 0; x < platforms.GetLength(1); x++)
            {
                if (platforms[y, x])
                {
                    Console.Error.Write(_platformChar);
                }
                else
                {
                    bool charPlaced = false;
                    // check if a snake is in this position
                    foreach (var bot in mySnakeBots)
                    {
                        if (bot.Body.Any(p => p.X == x && p.Y == y))
                        {
                            if (bot.Body[0].X == x && bot.Body[0].Y == y)
                            {                                
                                Console.Error.Write(_mySnakeHeadChar);
                                charPlaced = true;
                                break;
                            }
                            else
                            {
                                Console.Error.Write(_mySnakeBodyChar);
                                charPlaced = true;
                                break;
                            }
                        }
                    }

                    if (charPlaced)
                    {
                        continue;
                    }

                    foreach (var bot in opponentSnakeBots)
                    {
                        if (bot.Body.Any(p => p.X == x && p.Y == y))
                        {
                            if (bot.Body[0].X == x && bot.Body[0].Y == y)
                            {
                                Console.Error.Write(_opponentSnakeHeadChar);
                                charPlaced = true;
                                break;
                            }
                            else
                            {
                                Console.Error.Write(_opponentSnakeBodyChar);
                                charPlaced = true;
                                break;
                            }
                        }
                    }

                    if (charPlaced)
                    {
                        continue;
                    }

                    foreach(var powerUp in powerSources)
                    {
                        if (powerUp.X == x && powerUp.Y == y)
                        {
                            Console.Error.Write(_powerUpChar);
                            charPlaced = true;
                            break;
                        }
                    }

                    if (charPlaced)
                    {
                        continue;
                    }



                    Console.Error.Write(_emptySpaceChar);
                }
            }
            Console.Error.WriteLine();
        }
    }
}

internal sealed class Node
{
    public Point Position { get; set; }

    public Point Parent { get; set; }

    public int G { get; set; }
    public int H { get; set; }
    public int F { get; set; }

    public bool Closed { get; set; }

    public Node(Point position)
    {
        Position = position;
    }
}


internal sealed class PathFinder
{
    private Game _game;

    public PathFinder(Game game)
    {
        _game = game;
    }

    internal List<Point> GetShortestPath(Point startPoint, Point targetPoint, SnakeBot snake)
    {
        List<Node> nodes = new List<Node>();

        Node currentNode = new Node(startPoint);
        nodes.Add(currentNode);

        bool targetFound = false;

        while (!targetFound)
        {
            if (nodes.Count(n => n.Closed == false) == 0)
            {
                return new List<Point>();
            }

            Point[] pointsToCheck = new Point[4];

            // Prioritise heading towards the target as the first move
            if (Math.Abs(startPoint.X - targetPoint.X) >= Math.Abs(startPoint.Y - targetPoint.Y))
            {
                pointsToCheck[0] = new Point(Math.Min(_game.Width - 1, currentNode.Position.X + 1), currentNode.Position.Y);
                pointsToCheck[1] = new Point(Math.Max(0, currentNode.Position.X - 1), currentNode.Position.Y);
                pointsToCheck[2] = new Point(currentNode.Position.X, Math.Min(_game.Height - 1, currentNode.Position.Y + 1));
                pointsToCheck[3] = new Point(currentNode.Position.X, Math.Max(0, currentNode.Position.Y - 1));
            }
            else
            {
                pointsToCheck[0] = new Point(currentNode.Position.X, Math.Min(_game.Height - 1, currentNode.Position.Y + 1));
                pointsToCheck[1] = new Point(currentNode.Position.X, Math.Max(0, currentNode.Position.Y - 1));
                pointsToCheck[2] = new Point(Math.Min(_game.Width - 1, currentNode.Position.X + 1), currentNode.Position.Y);
                pointsToCheck[3] = new Point(Math.Max(0, currentNode.Position.X - 1), currentNode.Position.Y);
            }

            foreach (Point pointToCheck in pointsToCheck)
            {
                Node? existingNode = nodes.SingleOrDefault(n => n.Position == pointToCheck);

                if (existingNode == null)
                {
                    if (pointToCheck == startPoint
                        || pointToCheck == targetPoint
                        || (!IsPlatform(pointToCheck)
                            && IsValidMove(pointToCheck)))
                    {
                        Node node = new Node(pointToCheck);

                        node.Parent = currentNode.Position;

                        node.G = currentNode.G + 1;

                        node.H = CalculationUtil.GetManhattanDistance(pointToCheck, targetPoint);
                        node.F = node.G + node.H;

                        nodes.Add(node);
                    }
                }
                else
                {
                    if (!existingNode.Closed)
                    {
                        int g = currentNode.G + 1;

                        if (g < existingNode.G)
                        {
                            existingNode.G = g;

                            existingNode.F = existingNode.G + existingNode.H;

                            existingNode.Parent = currentNode.Position;
                        }
                    }
                }
            }

            currentNode.Closed = true;

            if (currentNode.Position == targetPoint)
            {
                targetFound = true;
            }
            else
            {
                nodes = nodes.OrderBy(n => n.Closed == true).ThenBy(n => n.F).ToList();

                currentNode = nodes.First();
            }
        }

        int numberOfSteps = currentNode.G;

        List<Point> shortestPath = [currentNode.Position];

        bool atStart = false;

        while (!atStart)
        {
            currentNode = nodes.Single(n => n.Position == currentNode.Parent);

            if (currentNode.Position == startPoint)
            {
                atStart = true;
            }
            else
            {
                shortestPath.Insert(0, currentNode.Position);
            }
        }

        return shortestPath;
    }

    private bool IsValidMove(Point pointToCheck)
    {
        return true;
    }

    private bool IsPlatform(Point pointToCheck)
    {
        // Check that it's not a platform

        // Check that it's not a snakes head or body

        if (_game.IsPlatform(pointToCheck))
        {
            return true;
        }

        if (_game.IsSnakePart(pointToCheck, countTails: false))
        {
            return true; 
        }


        return false;
    }
}


internal class Player
{
    static void Main(string[] args)
    {        
        string[] inputs;
        int myId = int.Parse(Console.ReadLine());
        int width = int.Parse(Console.ReadLine());
        int height = int.Parse(Console.ReadLine());


        bool[,] platforms = new bool[height, width];
        for (int y = 0; y < height; y++)
        {            
            string row = Console.ReadLine();

            char[] splitRow = row.ToCharArray();
            for (int x = 0; x < width; x++)
            {
                platforms[y, x] = splitRow[x] == '#';
            }
        }

        Game game = new Game(width, height, platforms);

        int snakebotsPerPlayer = int.Parse(Console.ReadLine());
        for (int i = 0; i < snakebotsPerPlayer; i++)
        {
            int mySnakebotId = int.Parse(Console.ReadLine());
            game.AddMySnake(new SnakeBot(mySnakebotId));

        }
        for (int i = 0; i < snakebotsPerPlayer; i++)
        {
            int oppSnakebotId = int.Parse(Console.ReadLine());
            game.AddOpponentSnake(new SnakeBot(oppSnakebotId));
        }

        Logger.Platforms(platforms);

        // game loop
        while (true)
        {
            game.MarkAllSnakesForRemoval();

            game.RemoveAllPowerSources();
            int powerSourceCount = int.Parse(Console.ReadLine());
            for (int i = 0; i < powerSourceCount; i++)
            {
                inputs = Console.ReadLine().Split(' ');
                int x = int.Parse(inputs[0]);
                int y = int.Parse(inputs[1]);

                game.AddPowerSource(x, y);
            }

            int snakebotCount = int.Parse(Console.ReadLine());
            for (int i = 0; i < snakebotCount; i++)
            {
                inputs = Console.ReadLine().Split(' ');
                int snakebotId = int.Parse(inputs[0]);
                string body = inputs[1];

                SnakeBot snakeBot = game.GetSnake(snakebotId);

                if (snakeBot != null)
                {
                    snakeBot.Remove = false;
                    snakeBot.Body.Clear();
                    string[] segments = body.Split(':');
                    foreach (string segment in segments)
                    {
                        string[] coordinates = segment.Split(',');
                        int x = int.Parse(coordinates[0]);
                        int y = int.Parse(coordinates[1]);
                        snakeBot.Body.Add(new Point(x, y));
                    }
                }
            }

            game.RemoveMarkedSnakes();

            // Write an action using Console.WriteLine()
            // To debug: Console.Error.WriteLine("Debug messages...");

            // Logger.Snakes("My snake Bots", mySnakeBots);
            // Logger.Snakes("My snake Bots", mySnakeBots);

            List<string> actions = game.GetActions();   
            
            Console.WriteLine(string.Join(";", actions));
        }
    }
}


internal class SnakeBot
{
    internal int Id { get; }
    internal List<Point> Body { get; set; }
    
    internal bool Remove { get; set; }

    internal SnakeBot(int id)
    {
        Id = id;

        Body = new List<Point>();
    }
}



