/**************************************************************
  This file was generated by FileConcatenator.
  It combined all classes in the project to work in Codingame.
***************************************************************/

using System.Collections.Generic;
using System.Drawing;
using System;
using Microsoft.VisualBasic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using System.IO;
using System.Collections;

internal class BestPath
{
    internal int SourceTownId { get; private set; }
    internal int DestinationTownId { get; private set; }

    internal List<Point> shortestPath;

    internal BestPath(int sourceTownId, int destinationTownId)
    {
        SourceTownId = sourceTownId;
        DestinationTownId = destinationTownId;

        shortestPath = new List<Point>();
    }

    internal void SetShortestPath(List<Point> path)
    {
        shortestPath = path;
    }

    internal List<Point> GetShortestPath()
    {
        return shortestPath;
    }
}



internal class CalculationUtil
{
    internal static int GetManhattanDistance(Point startPosition, Point targetPosition)
    {
        return Math.Abs(startPosition.X - targetPosition.X) + Math.Abs(startPosition.Y - targetPosition.Y);
    }
}

internal enum CellType
{
    PLAINS = 0,
    RIVER = 1,
    MOUNTAIN = 2,
    POI = 3
}

public class Game
{
    private int _myId;

    private Map _map;

    private List<Town> _towns;

    private int _myScore;
    private int _opponentScore;

    private PathFinder _pathFinder;
    private RegionTracker _regionTracker;

    private List<(int, int)> _completedPaths;

    public Game(int myId)
    {
        _myId = myId;

        _towns = new List<Town>();
        _completedPaths = new List<(int, int)>();

        _regionTracker = new RegionTracker(_myId);
    }

    internal void SetMap(Map map)
    {
        _map = map;

        _pathFinder = new PathFinder(_map.Width, _map.Height);
    }

    internal void SetMyScore(int myScore)
    {
        _myScore = myScore;
    }

    internal void SetOpponentScore(int foeScore)
    {
        _opponentScore = foeScore;
    }

    internal void SetTowns(List<Town> towns)
    {
        _towns = towns;
    }

    internal string CalculateActions()
    {
        // TODO
        // 1. Analyse all best paths to desired towns (They can change when regions are inked)
        //      Q. Do I need to do it from scratch every time? I could persist best paths and only update when 
        //         a region is inked.
        // 2. Keep track of all regions and their states
        //      Q. As above, do I need to do it from scratch every time? I could persist regions and update
        //      Region class should hold: Id, IsInked, Instability level, list of optimal paths on it and who owns tracks on them. List of non-optimal
        //        tracks on them

        int actionPoints = 3; 
        // Logger.TypeMap(_map);

        // First pass
        // For all towns, for all desired paths, find the shortest path to the desired town
        List<Point> shortest = new List<Point>();
        int shortestDistance = int.MaxValue;

        foreach (var town in _towns)
        {
            foreach (var desiredConnection in town.DesiredConnections)
            {
                if (_completedPaths.Contains((town.Id, desiredConnection)))
                {
                    continue;
                }

                Town desiredTown = _towns.First(t => t.Id == desiredConnection);

                var shortestPath = _pathFinder.GetShortestPath(new Point(town.X, town.Y), new Point(desiredTown.X, desiredTown.Y), _regionTracker.GetExcludePoints());

                if (shortestPath.Count < shortestDistance)
                {
                    // Don't count the target town as part of the path
                    if (shortestPath.Count > 0)
                    {
                        shortestPath.RemoveAt(shortestPath.Count - 1);

                        for (int i = shortestPath.Count-1; i >= 0; i--)
                        {
                            var point = shortestPath[i];
                            if (_towns.Any(t => t.X == point.X && t.Y == point.Y))
                            {
                                shortestPath.RemoveAt(i);
                                i--;
                            }
                        }
                    }

                    // If it's 100% tracked find something else
                    if (IsAlreadyTracked(shortestPath))
                    {
                        // Add to list of completed paths so we don't try to do it again
                        _completedPaths.Add((town.Id, desiredTown.Id));
                    }
                    else
                    {
                        shortestDistance = shortestPath.Count;
                        shortest = shortestPath;
                    }
                }
            }
        }

        Logger.Message($"Shortest path found is {shortestDistance} steps with points : {string.Join(", ", shortest.Select(p => $"({p.X}, {p.Y})"))}");

        // Work out what tracks I can make
        List<(Point, CellType)> cellTypes = new List<(Point, CellType)>();

        foreach (var point in shortest)
        {
            if (_map.isTrackFree(point.X, point.Y))
            {
                CellType cellType = _map.CellTypes[point.X, point.Y];
                cellTypes.Add((point, cellType));
            }
        }

        Logger.Message($"Shortest untracked path found is: {string.Join(", ", cellTypes.Select(c => $"({c.Item1.X}, {c.Item1.Y})"))}");

        // Order by cell type, so we can prioritize plains over rivers and mountains
        List <(Point, CellType)> orderedCellTypes = cellTypes.OrderBy(ct => ct.Item2).ToList();

        var actions = string.Empty;

        bool stop = false;
        int count = 0;
        while (actionPoints > 0 && count < orderedCellTypes.Count && stop == false)
        {
            var (point, cellType) = orderedCellTypes[count];

            if ((int)cellType + 1 <= actionPoints)
            {
                actions += $"PLACE_TRACKS {point.X} {point.Y};";
                actionPoints -= (int)cellType + 1;
            }
            else
            {
                stop = true;
            }

            count++;
        }

        actions += GetDisruptAction();

        if (string.IsNullOrEmpty(actions))
        {
            actions = "WAIT;";
        }

        return actions;
    }

    private string GetDisruptAction()
    {
        int region = _regionTracker.GetStrongestEnemyRegion();

        return region != -1 ? $"DISRUPT {region};" : string.Empty;
    }

    private bool IsAlreadyTracked(List<Point> path)
    {
        foreach (var point in path)
        {
            if (_map.isTrackFree(point.X, point.Y))
            {
                return false;
            }
        }

        return true;
    }

    internal void UpdateCell(int x, int y, int tracksOwner, int instability, bool inked)
    {
        _map.SetTrack(x, y, tracksOwner);

        int regionId = _regionTracker.GetRegionId(x, y);

        _regionTracker.UpdateRegion(regionId, instability, inked);

        if (tracksOwner != -1)
        {
            _regionTracker.AddTrack(regionId, x, y, tracksOwner);
        }
    }

    internal void InitialiseCellToRegion(int x, int y, int regionId)
    {
        _regionTracker.AddCellToRegion(x, y, regionId);
    }

    internal void AddTownToRegion(int townId, int townX, int townY)
    {
        _regionTracker.AddTown(townId, townX, townY);
    }
}


internal static class Logger
{

    private static bool DISABLE_LOGGING = false;

    internal static void DisableLogging()
    {
        DISABLE_LOGGING = true;
    }

    internal static void EnableLogging()
    {
        DISABLE_LOGGING = false;
    }

    internal static void Error(string message)
    {
        Console.Error.WriteLine("ERROR: " + message);
    }

    internal static void Message(string message)
    {
        if (DISABLE_LOGGING) 
        {
            return;
        }

        Console.Error.WriteLine(message);
    }

    internal static void RegionMap(Map map)
    {      

    }

    internal static void TypeMap(Map map)
    {
        for (int y = 0; y < map.Height; y++)
        {
            for (int x = 0; x < map.Width; x++)
            {
                Console.Error.Write(ToSymbol(map.CellTypes[x, y]));
            }
            Console.Error.WriteLine();
        }
    }

    private static string ToSymbol(CellType cellType)
    {
        switch (cellType)
        {
                case CellType.PLAINS:
                    return " ";
                case CellType.RIVER:
                    return "~";
                case CellType.MOUNTAIN:
                    return "^";
                case CellType.POI:
                    return "*";
                default:
                    return " ";
        }
    }
}

internal class Map {
    internal int Width { get; }
    internal int Height { get; }

    internal CellType[,] CellTypes;
    internal int[,] Regions;

    private int[,] _trackOwner;


    internal Map(int width, int height)
    {
        Width = width;
        Height = height;

        CellTypes = new CellType[width, height];
        Regions = new int[width, height];

        _trackOwner = new int[width, height];
    }

    internal void SetCell(int x, int y, CellType cellType, int region)
    {
        CellTypes[x, y] = cellType;
        Regions[x, y] = region;
    }

    internal void SetTrack(int x, int y, int tracksOwner)
    {
        _trackOwner[x, y] = tracksOwner;
    }

    internal bool isTrackFree(int x, int y)
    {
        return _trackOwner[x, y] == -1;
    }
}

internal sealed class Node
{
    internal Point Position { get; set; }

    internal Node? Parent { get; set; }

    internal int G { get; set; }
    internal int H { get; set; }
    internal int F { get; set; }

    internal bool Closed { get; set; }

    // Track the move that leads to this node for tie-breaking equidistant paths
    internal Point? FirstMove { get; set; }

    internal Node(Point position)
    {
        Position = position;
    }
}



internal class PathFinder
{
    private readonly int _width;
    private readonly int _height;

    internal PathFinder(int width, int height)
    {
        _width = width;
        _height = height;
    }

    internal List<Point> GetShortestPath(Point startPosition, Point targetPosition, HashSet<Point>? excludePoints = null)
    {
        if (startPosition == targetPosition)
        {
            return new List<Point>();
        }

        var nodesByPos = new Dictionary<Point, Node>();
        var queue = new Queue<Node>();

        var startNode = new Node(startPosition)
        {
            G = 0,
            FirstMove = null
        };

        nodesByPos[startPosition] = startNode;
        queue.Enqueue(startNode);

        while (queue.Count > 0)
        {
            var current = queue.Dequeue();

            if (current.Position == targetPosition)
            {
                var path = new List<Point>();
                var node = current;

                while (node != null && node.Position != startPosition)
                {
                    path.Add(node.Position);
                    node = node.Parent;
                }

                path.Reverse();
                return path;
            }

            // Neighbour priority order: North, East, South, West
            var neighbours = new Point[4];
            neighbours[0] = new Point(current.Position.X, current.Position.Y - 1); // North
            neighbours[1] = new Point(current.Position.X + 1, current.Position.Y); // East
            neighbours[2] = new Point(current.Position.X, current.Position.Y + 1); // South
            neighbours[3] = new Point(current.Position.X - 1, current.Position.Y); // West

            foreach (var pt in neighbours)
            {
                // bounds check
                if (pt.X < 0 || pt.X >= _width || pt.Y < 0 || pt.Y >= _height)
                {
                    continue;
                }

                if (excludePoints != null && excludePoints.Contains(pt))
                {
                    continue;
                }

                // already visited
                if (nodesByPos.ContainsKey(pt))
                {
                    continue;
                }

                var node = new Node(pt)
                {
                    Parent = current,
                    G = current.G + 1,
                    FirstMove = current.Position == startPosition ? pt : current.FirstMove
                };

                nodesByPos[pt] = node;
                queue.Enqueue(node);
            }
        }

        // no path found
        return new List<Point>();
    }
}

class Player
{
    static void Main(string[] args)
    {
        string[] inputs;
        int myId = int.Parse(Console.ReadLine()); // 0 or 1

        var game = new Game(myId);

        int width = int.Parse(Console.ReadLine()); // map size
        int height = int.Parse(Console.ReadLine());

        InitialiseMap(game, width, height);

        InitialiseTowns(game);



        // game loop
        while (true)
        {
            int myScore = int.Parse(Console.ReadLine());
            int foeScore = int.Parse(Console.ReadLine());

            game.SetMyScore(myScore);
            game.SetOpponentScore(foeScore);

            for (int i = 0; i < height; i++)
            {
                for (int j = 0; j < width; j++)
                {
                    inputs = Console.ReadLine().Split(' ');
                    int tracksOwner = int.Parse(inputs[0]);
                    

                    int instability = int.Parse(inputs[1]); // region inked (destroyed) when this >= 3.
                    bool inked = inputs[2] != "0"; // true if region is destroyed.

                    game.UpdateCell(j, i, tracksOwner, instability, inked);

                    string partOfActiveConnections = inputs[3]; // if this cell is part of one or more railway connections, this will be town ids (separated by -) in a list separated by commas. e.g. 0-1,1-2,1-3. "x" otherwise.
                }
            }

            string actions = game.CalculateActions();

            // Write an action using Console.WriteLine()
            // To debug: Console.Error.WriteLine("Debug messages...");


            // AUTOPLACE x1 y1 x2 | PLACE_TRACKS x y | DISRUPT regionId | MESSAGE text
            Console.WriteLine(actions);
        }
    }

    private static void InitialiseMap(Game game, int width, int height)
    {
        var map = new Map(width, height);

        for (int i = 0; i < height; i++)
        {
            for (int j = 0; j < width; j++)
            {
                var inputs = Console.ReadLine().Split(' ');
                int regionId = int.Parse(inputs[0]);
                int type = int.Parse(inputs[1]); // 0 (PLAINS), 1 (RIVER), 2 (MOUNTAIN), 3 (POI)

                map.SetCell(j, i, (CellType)type, regionId);
                game.InitialiseCellToRegion(j, i, regionId);
            }
        }

        game.SetMap(map);
    }

    private static void InitialiseTowns(Game game)
    {
        List<Town> towns = new List<Town>();
        int townCount = int.Parse(Console.ReadLine());
        for (int i = 0; i < townCount; i++)
        {
            var inputs = Console.ReadLine().Split(' ');
            int townId = int.Parse(inputs[0]);
            int townX = int.Parse(inputs[1]);
            int townY = int.Parse(inputs[2]);
            string desiredConnections = inputs[3]; // comma-separated town ids e.g. 0,1,2,3

            List<int> desiredConnectionsList = new List<int>();
            if (desiredConnections != "x")
            {
                desiredConnectionsList = desiredConnections.Split(',').Select(int.Parse).ToList();
            }

            var town = new Town(townId, townX, townY, desiredConnectionsList);
            towns.Add(town);

            game.AddTownToRegion(townId, townX, townY);
        }

        game.SetTowns(towns);
    }
}


internal class Region
{
    internal int Id { get; private set; }

    internal bool IsInked { get; private set; } = false;

    internal bool HasTown { get; set; } = false;

    internal int Instability { get; private set; }

    private HashSet<Point> _cells;
    private HashSet<Point> _allTracks;
    private HashSet<Point> _myTracks;
    private HashSet<Point> _opponentTracks;
    private HashSet<Point> _jointTracks;

    public Region(int id)
    {
        Id = id;
        _cells = new HashSet<Point>();
        _allTracks = new HashSet<Point>();
        _myTracks = new HashSet<Point>();
        _opponentTracks = new HashSet<Point>();
        _jointTracks = new HashSet<Point>();
    }

    internal void AddCell(int x, int y)
    {
        _cells.Add(new Point(x, y));
    }

    internal IEnumerable<Point> GetCells()
    {
        return _cells;
    }

    internal void AddJointTrack(int x, int y)
    {
        if (IsInked)
        {
            return;
        }

        _jointTracks.Add(new Point(x, y));
        _allTracks.Add(new Point(x, y));
    }

    internal void AddMyTrack(int x, int y)
    {
        if (IsInked)
        {
            return;
        }

        _myTracks.Add(new Point(x, y));
        _allTracks.Add(new Point(x, y));
    }

    internal void AddOpponentTrack(int x, int y)
    {
        if (IsInked)
        {
            return;
        }

        _opponentTracks.Add(new Point(x, y));
        _allTracks.Add(new Point(x, y));
    }

    internal void UpdateInstability(int instability, bool inked)
    {
        Instability = instability;
        IsInked = inked;
    }

    internal int GetEnemyTracks()
    {
        return _opponentTracks.Count;
    }

    internal int GetMyTracks()
    {
        return _myTracks.Count;
    }
}

internal class RegionTracker
{
    private int _myId;
    private List<Region> _regions;

    public RegionTracker(int myId)
    {
        _myId = myId;
        _regions = new List<Region>();
    }

    internal void AddCellToRegion(int x, int y, int regionId)
    {
        Region? existingRegion = _regions.SingleOrDefault(r => r.Id == regionId);

        if (existingRegion == null)
        {
            Region region = new Region(regionId);
            region.AddCell(x, y);
            _regions.Add(region);
        }
        else
        {
            existingRegion.AddCell(x, y);
        }
    }

    internal HashSet<Point> GetExcludePoints()
    {
        HashSet<Point> excludePoints = new HashSet<Point>();

        foreach (var region in _regions)
        {
            if (region.IsInked)
            {
                excludePoints.UnionWith(region.GetCells());
            }
        }

        return excludePoints;
    }

    internal int GetRegionId(int x, int y)
    {
        Region? region = _regions.SingleOrDefault(r => r.GetCells().Contains(new Point(x, y)));

        if (region == null)
        {
            Logger.Error($"Region not found for cell ({x}, {y}) in GetRegionId");
            return -1;
        }

        return region.Id;
    }

    internal void AddTrack(int regionId, int x, int y, int tracksOwner)
    {
        Region? region = _regions.SingleOrDefault(r => r.GetCells().Contains(new Point(x, y)));

        if (region == null)
        {
            Logger.Error($"Region not found for cell ({x}, {y}) in AddTrack");
            return;
        }

        if (tracksOwner == -1)
        {
            return;
        }

        if (tracksOwner == 2)
        {
            region.AddJointTrack(x, y);
        }

        if (_myId == 0)
        {
            if (tracksOwner == 0)
            {
                region.AddMyTrack(x, y);
            }
            else if (tracksOwner == 1)
            {
                region.AddOpponentTrack(x, y);
            }
        }
        else
        {
            if (tracksOwner == 0)
            {
                region.AddOpponentTrack(x, y);                
            }
            else if (tracksOwner == 1)
            {
                region.AddMyTrack(x, y);
            }
        }
    }

    internal void UpdateRegion(int regionId, int instability, bool inked)
    {
        Region? region = _regions.SingleOrDefault(r => r.Id == regionId);

        if (region == null)
        {
            Logger.Error($"Region not found for id {regionId} in UpdateRegion");
        }

        region.UpdateInstability(instability, inked);
    }

    // First pass at getting a disrupt action
    // For every region calculate enemyTracks - myTracks, Choose the region with the highest
    // score
    internal int GetStrongestEnemyRegion()
    {
        // For every region calculate enemyTracks -myTracks, Choose the region with the highest score
        int strongestEnemyRegion = int.MinValue;
        int strongerstEnemyRegionId = -1;

        foreach (Region region in _regions) 
        {
            if (region.IsInked || region.HasTown)
            {
                continue;
            }

            int score = region.GetEnemyTracks() - region.GetMyTracks();

            if (score > strongestEnemyRegion && score > 0)
            {
                strongestEnemyRegion = score;
                strongerstEnemyRegionId = region.Id;
            }
        }

        return strongerstEnemyRegionId;
    }

    internal void AddTown(int townId, int townX, int townY)
    {
        Region? region = _regions.SingleOrDefault(r => r.GetCells().Contains(new Point(townX, townY)));

        if (region == null)
        {
            Logger.Error($"Region not found for cell ({townX}, {townY}) in AddTown");
            return;
        }

        region.HasTown = true;
    }
}

internal class Town
{
    internal int Id { get; private set; }

    internal int X { get; private set; }

    internal int Y { get; private set; }

    internal List<int> DesiredConnections { get; private set; }

    internal Town(int id, int x, int y, List<int> desiredConnections)
    {
        Id = id;
        X = x;
        Y = y;
        DesiredConnections = desiredConnections;
    }
}


