namespace WinterChallenge2024;

internal enum ActionResult
{
    ATTACK_ORGAN,
    ATTACK_ROOT,
    CONSUME_A_PROTEIN,
    CONSUME_B_PROTEIN,
    CONSUME_C_PROTEIN,
    CONSUME_D_PROTEIN,
    HARVEST_A_PROTEIN,
    HARVEST_B_PROTEIN,
    HARVEST_C_PROTEIN,
    HARVEST_D_PROTEIN,
    SPORE
}
